#AI Explorer

In [1]:
from google import genai
import time
from google.genai.errors import ServerError

# ============================================================
# 1. GEMINI API KEY
# ============================================================

api_key = ""

client = genai.Client(api_key=api_key)

print("Gemini client created successfully!")


# ============================================================
# 2. AI TEACHER INSTRUCTIONS
# ============================================================

TEACHER_INSTRUCTIONS = """
You are an expert AI Teacher.

Your job is to teach students, not just provide answers.

Teaching rules:
- Give only a simple explanation of the concept.
- Use easy, layman terms.
- Be precise.
- Answer in exactly 3 short lines.
- Do not use complicated technical language unless necessary.
"""


# ============================================================
# 3. AI TEACHER FUNCTION
# ============================================================

def ask_teacher(question, subject, student_level, language):

    user_message = f"""
{TEACHER_INSTRUCTIONS}

Subject: {subject}
Student level: {student_level}
Language: {language}

Student question:
{question}
"""

    # Try 3 times if Gemini is temporarily busy
    for attempt in range(3):

        try:

            response = client.models.generate_content(
                model="gemini-3.8-flash",
                contents=user_message
            )

            # Gemini's generated answer
            answer = response.text

            return answer

        except ServerError:

            if attempt < 2:

                wait_time = 5 * (attempt + 1)

                print(
                    f"\nGemini is temporarily busy. "
                    f"Retrying in {wait_time} seconds..."
                )

                time.sleep(wait_time)

            else:

                return (
                    "Gemini is currently busy. "
                    "Please try again in a moment."
                )


# ============================================================
# 4. CHAT APPLICATION
# ============================================================

def start_teacher():

    print("=" * 60)
    print("                 AI TEACHER")
    print("=" * 60)

    print("Type 'exit' to stop.\n")

    while True:

        question = input("Student: ")

        if question.lower() == "exit":

            print("\nTeacher: Keep learning! 👋")
            break

        answer = ask_teacher(
            question=question,
            subject="AI & Data Science",
            student_level="Beginner",
            language="English"
        )

        print("\nTeacher:")
        print(answer)

        print("\n" + "-" * 60)


# ============================================================
# 5. RUN
# ============================================================

if __name__ == "__main__":
    start_teacher()

Gemini client created successfully!
============================================================
                 AI TEACHER
============================================================
Type 'exit' to stop.

Student:  what is verbose?

Direct use of automatic function calling (AFC) in Models.generate_content is not recommended. Instead, we recommend to use AFC in Chat.send_message. Similarly, direct use of AFC in Models.generate_content_stream is not recommended. Instead, we recommend to use AFC in Chat.send_message_stream.

Gemini is temporarily busy. Retrying in 5 seconds...

Teacher:
"Verbose" is a setting that controls how much information a program shows you while it runs.
When turned on, it displays detailed progress, like step-by-step updates and training logs.
When turned off, the program works silently in the background without printing extra messages.

------------------------------------------------------------

Student:  exit

Teacher: Keep learning! 👋

In [2]:
from google import genai
import time
from google.genai.errors import ServerError

# ============================================================
# 1. GEMINI API KEY
# ============================================================

api_key = ""

client = genai.Client(api_key=api_key)

print("Gemini client created successfully!")


# ============================================================
# 2. AI TEACHER INSTRUCTIONS
# ============================================================

TEACHER_INSTRUCTIONS = """
You are an expert AI Teacher.

Your job is to teach students, not just provide answers.

Teaching rules:
- Give only a simple explanation of the concept.
- Use layman terms.
- Be precise.
- Answer in exactly 3 short lines.
- Do not use complicated language.
"""


# ============================================================
# 3. CONVERSATION MEMORY
# ============================================================

conversation = []


# ============================================================
# 4. AI TEACHER FUNCTION
# ============================================================

def ask_teacher(question, subject, student_level, language):

    user_message = f"""
{TEACHER_INSTRUCTIONS}

Subject: {subject}
Student level: {student_level}
Language: {language}

Question:
{question}
"""

    # Try up to 3 times if Gemini is temporarily unavailable
    for attempt in range(3):

        try:

            response = client.models.generate_content(
                model="gemini-3.8-flash",
                contents=user_message
            )

            # Get Gemini's answer
            answer = response.text

            # Store conversation history
            conversation.append({
                "role": "user",
                "content": user_message
            })

            conversation.append({
                "role": "assistant",
                "content": answer
            })

            return answer

        except ServerError:

            if attempt < 2:

                wait_time = 5 * (attempt + 1)

                print(
                    f"\nGemini is busy. "
                    f"Retrying in {wait_time} seconds..."
                )

                time.sleep(wait_time)

            else:

                return (
                    "Gemini is temporarily unavailable. "
                    "Please try again later."
                )


# ============================================================
# 5. CHAT APPLICATION
# ============================================================

def start_teacher():

    print("=" * 60)
    print("              AI TEACHER")
    print("=" * 60)

    print("Type 'exit' to stop.\n")

    while True:

        question = input("Student: ")

        if question.lower() == "exit":

            print("\nTeacher: Keep learning! 👋")
            break

        answer = ask_teacher(
            question=question,
            subject="AI & Data Science",
            student_level="Beginner",
            language="English"
        )

        print("\nTeacher:")
        print(answer)

        print("\n" + "-" * 60)


# ============================================================
# 6. RUN
# ============================================================

if __name__ == "__main__":
    start_teacher()

Gemini client created successfully!
============================================================
              AI TEACHER
============================================================
Type 'exit' to stop.

Student:  explain about FAISS?

Teacher:
FAISS is a tool made by Meta that helps computers find similar items in huge collections instantly.
Instead of looking for exact words, it compares things like photos or meanings to find the closest match.
Think of it like a super-fast search engine that spots look-alikes among millions of choices in seconds.

------------------------------------------------------------

Student:  what is the reusability?

Gemini is busy. Retrying in 5 seconds...

Gemini is busy. Retrying in 10 seconds...

Teacher:
Gemini is temporarily unavailable. Please try again later.

------------------------------------------------------------

Student:  exit

Teacher: Keep learning! 👋

In [5]:
from google import genai

# ============================================================
# 1. GEMINI API KEY
# ============================================================

api_key = ""

client = genai.Client(api_key=api_key)

print("Gemini client created successfully!")


# ============================================================
# 2. AI TEACHER INSTRUCTIONS
# ============================================================

TEACHER_INSTRUCTIONS = """
You are an expert AI Teacher.

Your job is to teach students, not just provide answers.

Teaching rules:
- Give only a simple explanation of the concept.
- Use layman terms.
- Answer should be precise and exactly 3 short lines.
- Explain the concept simply.
"""


# ============================================================
# 3. CONVERSATION MEMORY
# ============================================================

conversation = []


# ============================================================
# 4. AI TEACHER FUNCTION
# ============================================================

def ask_teacher(question, subject, student_level, language):

    user_message = f"""
{TEACHER_INSTRUCTIONS}

Subject: {subject}
Student level: {student_level}
Language: {language}

Question:
{question}
"""

    response = client.models.generate_content(
        model="gemini-3.8-flash",
        contents=user_message
    )

    answer = response.text

    return answer


# ============================================================
# 5. CHAT APPLICATION
# ============================================================

def start_teacher():

    print("=" * 60)
    print("              AI TEACHER")
    print("=" * 60)

    print("Type 'exit' to stop.\n")

    while True:

        question = input("Student: ")

        if question.lower() == "exit":

            print("\nTeacher: Keep learning! 👋")
            break

        answer = ask_teacher(
            question=question,
            subject="AI & Data Science",
            student_level="Beginner",
            language="English"
        )

        print("\nTeacher:")
        print(answer)

        print("\n" + "-" * 60)


# ============================================================
# 6. RUN
# ============================================================

if __name__ == "__main__":
    start_teacher()

Gemini client created successfully!
============================================================
              AI TEACHER
============================================================
Type 'exit' to stop.

Student:  what is agentic AI?

ServerError: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}

# Stage2 -  input Quries- Generate

In [7]:
import pandas as pd
import ollama
import time


# ============================================================
# 1. OLLAMA MODEL CONFIGURATION
# ============================================================

MODEL_NAME = "llama3.1"

print("Ollama configuration created successfully!")


# ============================================================
# 2. FILE CONFIGURATION
# ============================================================

INPUT_CSV = "ai_teacher_20_questions.csv"
OUTPUT_CSV = "ai_teacher_results.csv"


# ============================================================
# 3. LOAD DATASET
# ============================================================

df = pd.read_csv(INPUT_CSV)

print("Dataset loaded")
print(f"Number of questions: {len(df)}")


# ============================================================
# 4. AI TEACHER INSTRUCTIONS
# ============================================================

TEACHER_INSTRUCTIONS = """
You are an expert AI Teacher.

Your job is to teach students, not just provide answers.

Teaching rules:
- Give only a simple explanation of the concept.
- Use layman terms.
- Answer should be precise and exactly 3 short lines.
- Do not add headings.
- Do not add bullet points.
- Do not add extra information.

Response format:
Explain the concept simply.
"""


# ============================================================
# 5. GENERATE ANSWER WITH RETRY
# ============================================================

def generate_answer(question, max_retries=3):

    prompt = f"""
{TEACHER_INSTRUCTIONS}

Student Question:
{question}
"""

    for attempt in range(max_retries):

        try:

            response = ollama.chat(
                model=MODEL_NAME,
                messages=[
                    {
                        "role": "user",
                        "content": prompt
                    }
                ]
            )

            answer = response["message"]["content"].strip()

            return answer

        except Exception as e:

            print(f"⚠️ Ollama error: {e}")

            if attempt < max_retries - 1:

                wait_time = 2 ** attempt

                print(
                    f"Retrying in {wait_time} seconds..."
                )

                time.sleep(wait_time)

            else:

                return (
                    "The local AI model is unavailable "
                    "after multiple attempts."
                )


# ============================================================
# 6. GENERATE ANSWERS FOR ALL QUESTIONS
# ============================================================

generated_answers = []

for index, row in df.iterrows():

    question = row["User Query"]

    print("=" * 60)
    print(f"Processing {index + 1}/{len(df)}")
    print(f"Question: {question}")

    answer = generate_answer(question)

    generated_answers.append(answer)

    print(f"Generated Answer:\n{answer}")

    # Small delay between requests
    time.sleep(1)


# ============================================================
# 7. APPEND GENERATED ANSWER TO DATAFRAME
# ============================================================

df["GeneratedAnswer"] = generated_answers


# ============================================================
# 8. SELECT FINAL COLUMNS
# ============================================================

df = df[
    [
        "User Query",
        "Teacher Response",
        "GeneratedAnswer"
    ]
]


# ============================================================
# 9. SAVE RESULT
# ============================================================

df.to_csv(
    OUTPUT_CSV,
    index=False,
    encoding="utf-8-sig"
)


# ============================================================
# 10. DISPLAY RESULT
# ============================================================

print("\n" + "=" * 70)
print("AI TEACHER TEST COMPLETED")
print("=" * 70)

print(df.to_string(index=False))

print("\nResult saved to:")
print(OUTPUT_CSV)

Ollama configuration created successfully!
Dataset loaded
Number of questions: 20
============================================================
Processing 1/20
Question: What is AI?
Generated Answer:
AI stands for Artificial Intelligence, which is a computer system that can think and learn like a human. It uses data and algorithms to make decisions and solve problems. AI is a way to make machines smart and helpful.
============================================================
Processing 2/20
Question: How does AI differ from traditional programming?
Generated Answer:
AI can learn and adapt on its own, unlike traditional programming which is based on set rules. It uses data and algorithms to make decisions. This allows AI to improve over time and perform tasks more efficiently.
============================================================
Processing 3/20
Question: What is Machine Learning?
Generated Answer:
Machine Learning is a way for computers to get better at doing tasks without being programmed exactly how to do them. They learn from data and examples, like a student learning from experience. It helps computers make predictions and decisions on their own.
============================================================
Processing 4/20
Question: What is Deep Learning?
Generated Answer:
Deep Learning is a type of Machine Learning that uses multiple layers of processing. It's like a stack of filters that help computers recognize patterns in data. This makes computers really good at tasks like image recognition and speech understanding.
============================================================
Processing 5/20
Question: What is the difference between AI, ML, and Deep Learning?
Generated Answer:
Artificial Intelligence (AI) is the overall idea of machines thinking like humans.
Machine Learning (ML) is a type of AI that helps machines learn from data on their own.
Deep Learning is a sub-type of ML that uses complex neural networks to make decisions.
============================================================
Processing 6/20
Question: What is training data?
Generated Answer:
Training data is the information used to teach a machine. It's like a textbook for a computer. The data is fed into the machine to help it learn.
============================================================
Processing 7/20
Question: What is a Machine Learning model?
Generated Answer:
A Machine Learning model is a set of instructions that helps a computer learn from data. It looks for patterns and relationships in the data, and makes predictions based on what it's learned. The more data it's given, the better it becomes.
============================================================
Processing 8/20
Question: What is supervised learning?
Generated Answer:
A computer is shown a lot of examples of something, and it has to learn from them by making predictions or doing tasks. It's like a student learning from a teacher.
============================================================
Processing 9/20
Question: What is unsupervised learning?
Generated Answer:
Unsupervised learning is a type of machine learning where the computer is given data but no specific outcome to achieve. The computer then finds patterns and relationships within the data on its own. It's like a detective searching for clues.
============================================================
Processing 10/20
Question: What is reinforcement learning?
Generated Answer:
The computer learns by trial and error, making good choices to get a reward and avoiding bad ones to avoid a penalty. It's like a game where it figures out what works and what doesn't. It gets better with time and experience.
============================================================
Processing 11/20
Question: What is an LLM?
Generated Answer:
An LLM is a type of computer program that uses a large collection of texts to learn and generate human-like responses. It works by analyzing patterns and relationships in the texts, allowing it to understand language and answer questions. This helps machines communicate more effectively.
============================================================
Processing 12/20
Question: What is Generative AI?
Generated Answer:
Generative AI creates new content, like images, music, or text, that's similar to existing ones. It uses algorithms to learn patterns and styles, then generates new output based on what it's learned. This helps with tasks like writing stories or composing music.
============================================================
Processing 13/20
Question: What is a prompt?
Generated Answer:
A prompt is a question or a starting point for writing or discussion. It helps guide the thoughts and ideas. It's like a map to the solution or answer.
============================================================
Processing 14/20
Question: What is Prompt Engineering?
Generated Answer:
Prompt Engineering is the process of refining and optimizing the language used in a prompt to get a specific, accurate response from a model. It's like asking a librarian to find a specific book on a shelf. You give them the right words, and they find the right answer.
============================================================
Processing 15/20
Question: What is RAG?
Generated Answer:
RAG is a rating system used to track progress and achievements in various subjects or activities. It stands for Red, Amber, and Green, which indicate different levels of performance. Red means you need to work harder, Amber means you're making progress, and Green means you're doing well.
============================================================
Processing 16/20
Question: Why is RAG useful?
Generated Answer:
RAG is useful for evaluating student progress. It helps teachers know what students have mastered and what they need help with. It provides a clear understanding of their strengths and weaknesses.
============================================================
Processing 17/20
Question: What is a vector database?
Generated Answer:
A vector database is a type of database that stores and manages vectors, which are mathematical objects used for dimensionality reduction and similarity searches. It's useful for applications like image and text search. Vectors help find similarities and patterns in data.
============================================================
Processing 18/20
Question: What are embeddings?
Generated Answer:
Embeddings are like maps that help computers understand words or numbers by turning them into a specific location in space, so they can be compared and used in calculations. This way, similar things are close together. It's like geography, but for ideas.
============================================================
Processing 19/20
Question: What is an AI Agent?
Generated Answer:
An AI Agent is a program that can make decisions and take actions on its own. It's like a computer that thinks and acts like a person. It's designed to accomplish a specific task or goal.
============================================================
Processing 20/20
Question: How can AI be used in education?
Generated Answer:
AI can help teachers with grading and lesson planning. It can also assist with identifying students who need extra help. This way, teachers can focus on teaching and mentoring.

======================================================================
AI TEACHER TEST COMPLETED
======================================================================
                                               User Query                                                                                                                                                                             Teacher Response                                                                                                                                                                                                                                                                                  GeneratedAnswer
                                              What is AI? AI (Artificial Intelligence) is the ability of computers to perform tasks that normally require human intelligence, such as learning, reasoning, recognizing patterns, and making decisions.                                                                       AI stands for Artificial Intelligence, which is a computer system that can think and learn like a human. It uses data and algorithms to make decisions and solve problems. AI is a way to make machines smart and helpful.
         How does AI differ from traditional programming?                                  Traditional programs follow fixed rules written by humans. AI systems can learn patterns from data and use those patterns to make predictions or decisions.                                                                            AI can learn and adapt on its own, unlike traditional programming which is based on set rules. It uses data and algorithms to make decisions. This allows AI to improve over time and perform tasks more efficiently.
                                What is Machine Learning?      Machine Learning is a branch of AI where computers learn patterns from data and use those patterns to make predictions or decisions without being explicitly programmed for every case.                                Machine Learning is a way for computers to get better at doing tasks without being programmed exactly how to do them. They learn from data and examples, like a student learning from experience. It helps computers make predictions and decisions on their own.
                                   What is Deep Learning?                                             Deep Learning is a type of Machine Learning that uses neural networks with multiple layers to learn complex patterns from large amounts of data.                                     Deep Learning is a type of Machine Learning that uses multiple layers of processing. It's like a stack of filters that help computers recognize patterns in data. This makes computers really good at tasks like image recognition and speech understanding.
What is the difference between AI, ML, and Deep Learning?                  AI is the broad field of making machines intelligent. ML is a way to achieve AI by learning from data. Deep Learning is a type of ML that uses multi-layer neural networks.                              Artificial Intelligence (AI) is the overall idea of machines thinking like humans.\nMachine Learning (ML) is a type of AI that helps machines learn from data on their own.\nDeep Learning is a sub-type of ML that uses complex neural networks to make decisions.
                                   What is training data?                                            Training data is the data used to teach a Machine Learning model. The model studies patterns in this data so it can make predictions on new data.                                                                                                                                                Training data is the information used to teach a machine. It's like a textbook for a computer. The data is fed into the machine to help it learn.
                        What is a Machine Learning model?                                        A Machine Learning model is a mathematical system that learns patterns from data and uses those learned patterns to produce predictions or decisions.                                                 A Machine Learning model is a set of instructions that helps a computer learn from data. It looks for patterns and relationships in the data, and makes predictions based on what it's learned. The more data it's given, the better it becomes.
                             What is supervised learning?                           Supervised learning trains a model using examples that already have known answers, such as customer information paired with whether the customer left the company.                                                                                                                             A computer is shown a lot of examples of something, and it has to learn from them by making predictions or doing tasks. It's like a student learning from a teacher.
                           What is unsupervised learning?                                        Unsupervised learning works with data that does not have predefined answers. The model tries to discover patterns, groups, or structures in the data.                                               Unsupervised learning is a type of machine learning where the computer is given data but no specific outcome to achieve. The computer then finds patterns and relationships within the data on its own. It's like a detective searching for clues.
                          What is reinforcement learning?                                                      Reinforcement learning teaches an agent through rewards and penalties. The agent learns which actions produce better results over time.                                                                The computer learns by trial and error, making good choices to get a reward and avoiding bad ones to avoid a penalty. It's like a game where it figures out what works and what doesn't. It gets better with time and experience.
                                          What is an LLM?                                                             An LLM, or Large Language Model, is an AI model trained on large amounts of text to understand and generate human-like language. An LLM is a type of computer program that uses a large collection of texts to learn and generate human-like responses. It works by analyzing patterns and relationships in the texts, allowing it to understand language and answer questions. This helps machines communicate more effectively.
                                   What is Generative AI?                                                       Generative AI is AI that can create new content such as text, images, audio, video, or code based on patterns learned during training.                           Generative AI creates new content, like images, music, or text, that's similar to existing ones. It uses algorithms to learn patterns and styles, then generates new output based on what it's learned. This helps with tasks like writing stories or composing music.
                                        What is a prompt?                                       A prompt is the instruction or input given to an AI model to tell it what you want it to do, such as explain a concept, write code, or summarize text.                                                                                                                                          A prompt is a question or a starting point for writing or discussion. It helps guide the thoughts and ideas. It's like a map to the solution or answer.
                              What is Prompt Engineering?                                                 Prompt Engineering is the practice of designing clear and effective instructions so an AI model produces more useful and reliable responses.                    Prompt Engineering is the process of refining and optimizing the language used in a prompt to get a specific, accurate response from a model. It's like asking a librarian to find a specific book on a shelf. You give them the right words, and they find the right answer.
                                             What is RAG?             RAG stands for Retrieval-Augmented Generation. It retrieves relevant information from external data sources and provides that information to an LLM before generating an answer. RAG is a rating system used to track progress and achievements in various subjects or activities. It stands for Red, Amber, and Green, which indicate different levels of performance. Red means you need to work harder, Amber means you're making progress, and Green means you're doing well.
                                       Why is RAG useful?                              RAG is useful when an AI application needs to answer questions using specific or changing information, such as company documents, policies, or knowledge bases.                                                                                             RAG is useful for evaluating student progress. It helps teachers know what students have mastered and what they need help with. It provides a clear understanding of their strengths and weaknesses.
                               What is a vector database?                                         A vector database stores numerical representations called embeddings and allows applications to search for information based on semantic similarity.                 A vector database is a type of database that stores and manages vectors, which are mathematical objects used for dimensionality reduction and similarity searches. It's useful for applications like image and text search. Vectors help find similarities and patterns in data.
                                     What are embeddings?                 Embeddings are numerical representations of text, images, or other data. Similar meanings tend to have similar vector representations, which makes semantic search possible.                                   Embeddings are like maps that help computers understand words or numbers by turning them into a specific location in space, so they can be compared and used in calculations. This way, similar things are close together. It's like geography, but for ideas.
                                     What is an AI Agent?                            An AI Agent is a system that can understand a goal, decide what actions are needed, use tools when necessary, and work through multiple steps to complete a task.                                                                                                      An AI Agent is a program that can make decisions and take actions on its own. It's like a computer that thinks and acts like a person. It's designed to accomplish a specific task or goal.
                         How can AI be used in education?        AI can support education by explaining concepts, generating practice questions, adapting lessons to student levels, providing feedback, and helping students learn at their own pace.                                                                                                                 AI can help teachers with grading and lesson planning. It can also assist with identifying students who need extra help. This way, teachers can focus on teaching and mentoring.

Result saved to:
ai_teacher_results.csv

# Stage3 - LLM Evaluation- Answer Quality

In [8]:
pip install -U deepeval ollama

Collecting deepevalNote: you may need to restart the kernel to use updated packages.

  Downloading deepeval-4.2.8-py3-none-any.whl.metadata (31 kB)
Requirement already satisfied: ollama in c:\users\manju\anaconda3\lib\site-packages (0.6.3)
Requirement already satisfied: aiohttp in c:\users\manju\anaconda3\lib\site-packages (from deepeval) (3.14.1)
Collecting click<8.4.0,>=8.0.0 (from deepeval)
  Downloading click-8.3.3-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: grpcio<2.0.0,>=1.67.1 in c:\users\manju\anaconda3\lib\site-packages (from deepeval) (1.81.1)
Requirement already satisfied: jinja2 in c:\users\manju\anaconda3\lib\site-packages (from deepeval) (3.1.6)
Requirement already satisfied: nest_asyncio in c:\users\manju\anaconda3\lib\site-packages (from deepeval) (1.6.0)
Requirement already satisfied: openai in c:\users\manju\anaconda3\lib\site-packages (from deepeval) (2.46.0)
Requirement already satisfied: opentelemetry-api<2.0.0,>=1.24.0 in c:\users\manju\anaconda3\lib\site-packages (from deepeval) (1.45.0)
Requirement already satisfied: opentelemetry-sdk<2.0.0,>=1.24.0 in c:\users\manju\anaconda3\lib\site-packages (from deepeval) (1.45.0)
Requirement already satisfied: portalocker in c:\users\manju\anaconda3\lib\site-packages (from deepeval) (4.1.0)
Requirement already satisfied: posthog<8.0.0,>=7.0.0 in c:\users\manju\anaconda3\lib\site-packages (from deepeval) (7.61.1)
Requirement already satisfied: pydantic<3.0.0,>=2.11.7 in c:\users\manju\anaconda3\lib\site-packages (from deepeval) (2.13.4)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in c:\users\manju\anaconda3\lib\site-packages (from deepeval) (2.14.2)
Collecting pyfiglet (from deepeval)
  Downloading pyfiglet-1.0.4-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: pytest in c:\users\manju\anaconda3\lib\site-packages (from deepeval) (9.0.3)
Collecting pytest-asyncio (from deepeval)
  Downloading pytest_asyncio-1.4.0-py3-none-any.whl.metadata (4.1 kB)
Collecting pytest-repeat (from deepeval)
  Downloading pytest_repeat-0.9.4-py3-none-any.whl.metadata (4.9 kB)
Collecting pytest-rerunfailures (from deepeval)
  Downloading pytest_rerunfailures-16.7-py3-none-any.whl.metadata (33 kB)
Collecting pytest-xdist (from deepeval)
  Downloading pytest_xdist-3.8.0-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: python-dotenv<2.0.0,>=1.1.1 in c:\users\manju\anaconda3\lib\site-packages (from deepeval) (1.2.4)
Collecting questionary<3.0.0,>=2.0.0 (from deepeval)
  Downloading questionary-2.1.1-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: requests<3.0.0,>=2.31.0 in c:\users\manju\anaconda3\lib\site-packages (from deepeval) (2.34.2)
Collecting rich<15.0.0,>=13.6.0 (from deepeval)
  Downloading rich-14.3.4-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: setuptools in c:\users\manju\anaconda3\lib\site-packages (from deepeval) (84.0.0)
Collecting tabulate<0.10.0,>=0.9.0 (from deepeval)
  Downloading tabulate-0.9.0-py3-none-any.whl.metadata (34 kB)
Requirement already satisfied: tenacity<=10.0.0,>=8.0.0 in c:\users\manju\anaconda3\lib\site-packages (from deepeval) (9.1.4)
Requirement already satisfied: tqdm<5.0.0,>=4.66.1 in c:\users\manju\anaconda3\lib\site-packages (from deepeval) (4.68.2)
Requirement already satisfied: typer<1.0.0,>=0.9 in c:\users\manju\anaconda3\lib\site-packages (from deepeval) (0.25.1)
Requirement already satisfied: wheel in c:\users\manju\anaconda3\lib\site-packages (from deepeval) (0.47.0)
Requirement already satisfied: colorama in c:\users\manju\anaconda3\lib\site-packages (from click<8.4.0,>=8.0.0->deepeval) (0.4.6)
Requirement already satisfied: typing-extensions~=4.12 in c:\users\manju\anaconda3\lib\site-packages (from grpcio<2.0.0,>=1.67.1->deepeval) (4.15.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.66b0 in c:\users\manju\anaconda3\lib\site-packages (from opentelemetry-sdk<2.0.0,>=1.24.0->deepeval) (0.66b0)
Requirement already satisfied: backoff>=1.10.0 in c:\users\manju\anaconda3\lib\site-packages (from posthog<8.0.0,>=7.0.0->deepeval) (2.2.1)
Requirement already satisfied: distro>=1.5.0 in c:\users\manju\anaconda3\lib\site-packages (from posthog<8.0.0,>=7.0.0->deepeval) (1.9.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\manju\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.11.7->deepeval) (0.6.0)
Requirement already satisfied: pydantic-core==2.46.4 in c:\users\manju\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.11.7->deepeval) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\manju\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.11.7->deepeval) (0.4.2)
Requirement already satisfied: prompt_toolkit<4.0,>=2.0 in c:\users\manju\anaconda3\lib\site-packages (from questionary<3.0.0,>=2.0.0->deepeval) (3.0.52)
Requirement already satisfied: wcwidth in c:\users\manju\anaconda3\lib\site-packages (from prompt_toolkit<4.0,>=2.0->questionary<3.0.0,>=2.0.0->deepeval) (0.2.14)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\manju\anaconda3\lib\site-packages (from requests<3.0.0,>=2.31.0->deepeval) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\manju\anaconda3\lib\site-packages (from requests<3.0.0,>=2.31.0->deepeval) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\manju\anaconda3\lib\site-packages (from requests<3.0.0,>=2.31.0->deepeval) (1.26.20)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\manju\anaconda3\lib\site-packages (from requests<3.0.0,>=2.31.0->deepeval) (2026.6.17)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\manju\anaconda3\lib\site-packages (from rich<15.0.0,>=13.6.0->deepeval) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\manju\anaconda3\lib\site-packages (from rich<15.0.0,>=13.6.0->deepeval) (2.20.0)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\manju\anaconda3\lib\site-packages (from typer<1.0.0,>=0.9->deepeval) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\manju\anaconda3\lib\site-packages (from typer<1.0.0,>=0.9->deepeval) (0.0.4)
Requirement already satisfied: httpx>=0.27 in c:\users\manju\anaconda3\lib\site-packages (from ollama) (0.28.1)
Requirement already satisfied: anyio in c:\users\manju\anaconda3\lib\site-packages (from httpx>=0.27->ollama) (4.12.1)
Requirement already satisfied: httpcore==1.* in c:\users\manju\anaconda3\lib\site-packages (from httpx>=0.27->ollama) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\manju\anaconda3\lib\site-packages (from httpcore==1.*->httpx>=0.27->ollama) (0.16.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\manju\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich<15.0.0,>=13.6.0->deepeval) (0.1.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\manju\anaconda3\lib\site-packages (from aiohttp->deepeval) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\manju\anaconda3\lib\site-packages (from aiohttp->deepeval) (1.4.0)
Requirement already satisfied: async-timeout<6.0,>=4.0 in c:\users\manju\anaconda3\lib\site-packages (from aiohttp->deepeval) (4.0.3)
Requirement already satisfied: attrs>=17.3.0 in c:\users\manju\anaconda3\lib\site-packages (from aiohttp->deepeval) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\manju\anaconda3\lib\site-packages (from aiohttp->deepeval) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\manju\anaconda3\lib\site-packages (from aiohttp->deepeval) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in c:\users\manju\anaconda3\lib\site-packages (from aiohttp->deepeval) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\manju\anaconda3\lib\site-packages (from aiohttp->deepeval) (1.24.2)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\manju\anaconda3\lib\site-packages (from anyio->httpx>=0.27->ollama) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\manju\anaconda3\lib\site-packages (from jinja2->deepeval) (3.0.3)
Requirement already satisfied: jiter<1,>=0.10.0 in c:\users\manju\anaconda3\lib\site-packages (from openai->deepeval) (0.16.0)
Requirement already satisfied: sniffio in c:\users\manju\anaconda3\lib\site-packages (from openai->deepeval) (1.3.1)
Requirement already satisfied: iniconfig>=1.0.1 in c:\users\manju\anaconda3\lib\site-packages (from pytest->deepeval) (2.3.0)
Requirement already satisfied: packaging>=22 in c:\users\manju\anaconda3\lib\site-packages (from pytest->deepeval) (24.2)
Requirement already satisfied: pluggy<2,>=1.5 in c:\users\manju\anaconda3\lib\site-packages (from pytest->deepeval) (1.6.0)
Requirement already satisfied: tomli>=1 in c:\users\manju\anaconda3\lib\site-packages (from pytest->deepeval) (2.4.0)
Collecting backports-asyncio-runner<2,>=1.1 (from pytest-asyncio->deepeval)
  Downloading backports_asyncio_runner-1.2.0-py3-none-any.whl.metadata (7.5 kB)
Collecting execnet>=2.1 (from pytest-xdist->deepeval)
  Downloading execnet-2.1.2-py3-none-any.whl.metadata (2.9 kB)
Downloading deepeval-4.2.8-py3-none-any.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 1.5/1.5 MB 9.8 MB/s  0:00:00
Downloading click-8.3.3-py3-none-any.whl (110 kB)
Downloading questionary-2.1.1-py3-none-any.whl (36 kB)
Downloading rich-14.3.4-py3-none-any.whl (310 kB)
Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
Downloading pyfiglet-1.0.4-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 1.8/1.8 MB 11.0 MB/s  0:00:00
Downloading pytest_asyncio-1.4.0-py3-none-any.whl (16 kB)
Downloading backports_asyncio_runner-1.2.0-py3-none-any.whl (12 kB)
Downloading pytest_repeat-0.9.4-py3-none-any.whl (4.2 kB)
Downloading pytest_rerunfailures-16.7-py3-none-any.whl (23 kB)
Downloading pytest_xdist-3.8.0-py3-none-any.whl (46 kB)
Downloading execnet-2.1.2-py3-none-any.whl (40 kB)
Installing collected packages: tabulate, pyfiglet, execnet, click, backports-asyncio-runner, rich, questionary, pytest-xdist, pytest-rerunfailures, pytest-repeat, pytest-asyncio, deepeval

  Attempting uninstall: tabulate

    Found existing installation: tabulate 0.10.0

    Uninstalling tabulate-0.10.0:

      Successfully uninstalled tabulate-0.10.0

   ----------------------------------------  0/12 [tabulate]
   --- ------------------------------------  1/12 [pyfiglet]
   --- ------------------------------------  1/12 [pyfiglet]
   --- ------------------------------------  1/12 [pyfiglet]
   --- ------------------------------------  1/12 [pyfiglet]
   --- ------------------------------------  1/12 [pyfiglet]
   --- ------------------------------------  1/12 [pyfiglet]
   --- ------------------------------------  1/12 [pyfiglet]
   --- ------------------------------------  1/12 [pyfiglet]
   ------ ---------------------------------  2/12 [execnet]
  Attempting uninstall: click
   ------ ---------------------------------  2/12 [execnet]
    Found existing installation: click 8.5.0
   ------ ---------------------------------  2/12 [execnet]
   ---------- -----------------------------  3/12 [click]
    Uninstalling click-8.5.0:
   ---------- -----------------------------  3/12 [click]
      Successfully uninstalled click-8.5.0
   ---------- -----------------------------  3/12 [click]
   ---------- -----------------------------  3/12 [click]
   ------------- --------------------------  4/12 [backports-asyncio-runner]
  Attempting uninstall: rich
   ------------- --------------------------  4/12 [backports-asyncio-runner]
    Found existing installation: rich 15.0.0
   ------------- --------------------------  4/12 [backports-asyncio-runner]
   ---------------- -----------------------  5/12 [rich]
    Uninstalling rich-15.0.0:
   ---------------- -----------------------  5/12 [rich]
      Successfully uninstalled rich-15.0.0
   ---------------- -----------------------  5/12 [rich]
   ---------------- -----------------------  5/12 [rich]
   ---------------- -----------------------  5/12 [rich]
   ---------------- -----------------------  5/12 [rich]
   ---------------- -----------------------  5/12 [rich]
   ---------------- -----------------------  5/12 [rich]
   ---------------- -----------------------  5/12 [rich]
   ---------------- -----------------------  5/12 [rich]
   -------------------- -------------------  6/12 [questionary]
   ----------------------- ----------------  7/12 [pytest-xdist]
   ----------------------- ----------------  7/12 [pytest-xdist]
   --------------------------------- ------ 10/12 [pytest-asyncio]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ------------------------------------ --- 11/12 [deepeval]
   ---------------------------------------- 12/12 [deepeval]

Successfully installed backports-asyncio-runner-1.2.0 click-8.3.3 deepeval-4.2.8 execnet-2.1.2 pyfiglet-1.0.4 pytest-asyncio-1.4.0 pytest-repeat-0.9.4 pytest-rerunfailures-16.7 pytest-xdist-3.8.0 questionary-2.1.1 rich-14.3.4 tabulate-0.9.0

WARNING: Ignoring invalid distribution -f-models-official (c:\users\manju\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -f-models-official (c:\users\manju\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -f-models-official (c:\users\manju\anaconda3\lib\site-packages)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
conda-repo-cli 1.0.173+2.gf8332ec requires urllib3>=2.2.2, but you have urllib3 1.26.20 which is incompatible.
huggingface-hub 1.33.0 requires click<9.0.0,>=8.4.2, but you have click 8.3.3 which is incompatible.
tf-models-official 2.10.1 requires pyyaml<6.0,>=5.1, but you have pyyaml 6.0.3 which is incompatible.

In [9]:
import pandas as pd

from deepeval import evaluate
from deepeval.metrics import AnswerRelevancyMetric, GEval
from deepeval.test_case import LLMTestCase, SingleTurnParams
from deepeval.evaluate import AsyncConfig
from deepeval.models import OllamaModel


# ============================================================
# 1. LOAD DATA
# ============================================================

df = pd.read_csv("ai_teacher_results.csv")

print("Dataset loaded")
print(f"Number of questions: {len(df)}")


# ============================================================
# 2. OLLAMA EVALUATION MODEL
# ============================================================

judge_model = OllamaModel(
    model="llama3.1",
    base_url="http://localhost:11434",
    temperature=0
)

print("Ollama Llama 3.1 judge model configured!")


# ============================================================
# 3. CREATE TEST CASES
# ============================================================

test_cases = [
    LLMTestCase(
        input=row["User Query"],
        actual_output=row["GeneratedAnswer"],
        expected_output=row["Teacher Response"]
    )
    for _, row in df.iterrows()
]


# ============================================================
# 4. DEFINE CORRECTNESS METRIC
# ============================================================

correctness = GEval(
    name="Answer Correctness",

    model=judge_model,

    criteria="""
    Evaluate whether the generated answer is factually correct
    compared with the expected teacher answer.

    Give a high score when the important meaning and facts are correct.

    Penalize:
    - incorrect facts
    - contradictory information
    - missing important information

    Minor wording differences should not reduce the score.
    """,

    evaluation_params=[
        SingleTurnParams.ACTUAL_OUTPUT,
        SingleTurnParams.EXPECTED_OUTPUT
    ],

    async_mode=False
)


# ============================================================
# 5. DEFINE RELEVANCY METRIC
# ============================================================

relevancy = AnswerRelevancyMetric(
    model=judge_model,

    include_reason=False,

    async_mode=False
)


# ============================================================
# 6. DEFINE HELPFULNESS METRIC
# ============================================================

helpfulness = GEval(
    name="Helpfulness",

    model=judge_model,

    criteria="""
    Evaluate how helpful the generated answer is for a beginner student.

    A helpful answer should:

    1. Directly answer the student's question.
    2. Be easy to understand.
    3. Provide enough explanation.
    4. Avoid unnecessary information.
    5. Help the student understand the concept.
    """,

    evaluation_params=[
        SingleTurnParams.INPUT,
        SingleTurnParams.ACTUAL_OUTPUT
    ],

    async_mode=False
)


# ============================================================
# 7. RUN DEEPEVAL
# ============================================================

print("\nStarting DeepEval evaluation...")

result = evaluate(
    test_cases=test_cases,

    metrics=[
        correctness,
        relevancy,
        helpfulness
    ],

    async_config=AsyncConfig(run_async=False)
)


# ============================================================
# 8. COMPLETED
# ============================================================

print("\n" + "=" * 70)
print("DEEPEVAL EVALUATION COMPLETED")
print("=" * 70)

Dataset loaded
Number of questions: 20
Ollama Llama 3.1 judge model configured!

Starting DeepEval evaluation...

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using llama3.1 (Ollama), strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using llama3.1 (Ollama), strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using llama3.1 (Ollama), strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_0 (Passed 3 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_1                                                                                                 │
│  ├──   Input:              How does AI differ from traditional programming?                                     │
│  │     Actual Output:      AI can learn and adapt on its own, unlike traditional programming which is based     │
│  │                         on set rules. It uses data and algorithms to make decisions. This allows AI to       │
│  │                         improve over time and perform tasks more efficiently.                                │
│  │     Expected Output:    Traditional programs follow fixed rules written by humans. AI systems can learn      │
│  │                         patterns from data and use those patterns to make predictions or decisions.          │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric                     ┃ Score ┃ Threshold ┃ Reason                                          │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        FAIL  │ Answer Correctness [GEval] │ 0.20  │ 0.50      │ The Actual Output contains several factual      │
│              │                            │       │           │ discrepancies and contradictory information     │
│              │                            │       │           │ compared to the Expected Output. For            │
│              │                            │       │           │ instance, it incorrectly states that AI can     │
│              │                            │       │           │ learn and adapt on its own, whereas the         │
│              │                            │       │           │ Expected Output accurately describes            │
│              │                            │       │           │ traditional programs as following fixed         │
│              │                            │       │           │ rules. Additionally, the Actual Output          │
│              │                            │       │           │ introduces new information about AI improving   │
│              │                            │       │           │ over time, which is not present in the          │
│              │                            │       │           │ Expected Output.                                │
│        PASS  │ Answer Relevancy           │ 1.00  │ 0.50      │ N/A                                             │
│        PASS  │ Helpfulness [GEval]        │ 0.90  │ 0.50      │ The Actual Output answer directly addresses     │
│              │                            │       │           │ the...                                          │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_2 (Passed 3 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_3 (Passed 3 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_4 (Passed 3 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_5 (Passed 3 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_6 (Passed 3 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_7                                                                                                 │
│  ├──   Input:              What is supervised learning?                                                         │
│  │     Actual Output:      A computer is shown a lot of examples of something, and it has to learn from them    │
│  │                         by making predictions or doing tasks. It's like a student learning from a            │
│  │                         teacher.                                                                             │
│  │     Expected Output:    Supervised learning trains a model using examples that already have known            │
│  │                         answers, such as customer information paired with whether the customer left the      │
│  │                         company.                                                                             │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric                     ┃ Score ┃ Threshold ┃ Reason                                          │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        FAIL  │ Answer Correctness [GEval] │ 0.40  │ 0.50      │ The Actual Output contains some correct         │
│              │                            │       │           │ concepts, such as learning from examples, but   │
│              │                            │       │           │ it introduces new and incorrect information,    │
│              │                            │       │           │ like comparing it to a student learning from    │
│              │                            │       │           │ a teacher. It also lacks the specific details   │
│              │                            │       │           │ about supervised learning, like customer        │
│              │                            │       │           │ information paired with known answers.          │
│        PASS  │ Answer Relevancy           │ 1.00  │ 0.50      │ N/A                                             │
│        PASS  │ Helpfulness [GEval]        │ 0.80  │ 0.50      │ The Actual Output answer directly answers the   │
│              │                            │       │           │ I...                                            │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_8 (Passed 3 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_9 (Passed 3 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_10 (Passed 3 metrics)                                                                              │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_11 (Passed 3 metrics)                                                                              │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_12                                                                                                │
│  ├──   Input:              What is a prompt?                                                                    │
│  │     Actual Output:      A prompt is a question or a starting point for writing or discussion. It helps       │
│  │                         guide the thoughts and ideas. It's like a map to the solution or answer.             │
│  │     Expected Output:    A prompt is the instruction or input given to an AI model to tell it what you        │
│  │                         want it to do, such as explain a concept, write code, or summarize text.             │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric                     ┃ Score ┃ Threshold ┃ Reason                                          │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        FAIL  │ Answer Correctness [GEval] │ 0.40  │ 0.50      │ The Actual Output contains some correct         │
│              │                            │       │           │ facts, but it also introduces new and           │
│              │                            │       │           │ incorrect information, such as comparing a      │
│              │                            │       │           │ prompt to a map. The important meaning and      │
│              │                            │       │           │ facts in the Actual Output are not entirely     │
│              │                            │       │           │ correct.                                        │
│        PASS  │ Answer Relevancy           │ 1.00  │ 0.50      │ N/A                                             │
│        PASS  │ Helpfulness [GEval]        │ 0.80  │ 0.50      │ The Actual Output answer directly answers the   │
│              │                            │       │           │ I...                                            │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_13 (Passed 3 metrics)                                                                              │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_14                                                                                                │
│  ├──   Input:              What is RAG?                                                                         │
│  │     Actual Output:      RAG is a rating system used to track progress and achievements in various            │
│  │                         subjects or activities. It stands for Red, Amber, and Green, which indicate          │
│  │                         different levels of performance. Red means you need to work harder, Amber means      │
│  │                         you're making progress, and Green means you're doing well.                           │
│  │     Expected Output:    RAG stands for Retrieval-Augmented Generation. It retrieves relevant information     │
│  │                         from external data sources and provides that information to an LLM before            │
│  │                         generating an answer.                                                                │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric                     ┃ Score ┃ Threshold ┃ Reason                                          │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        FAIL  │ Answer Correctness [GEval] │ 0.00  │ 0.50      │ The Actual Output contains incorrect facts      │
│              │                            │       │           │ and contradictory information. It describes     │
│              │                            │       │           │ RAG as a rating system, whereas the Expected    │
│              │                            │       │           │ Output correctly identifies it as a             │
│              │                            │       │           │ retrieval-augmented generation system.          │
│              │                            │       │           │ Additionally, the Actual Output introduces      │
│              │                            │       │           │ new information about the meaning of Red,       │
│              │                            │       │           │ Amber, and Green, which is not present in the   │
│              │                            │       │           │ Expected Output.                                │
│        PASS  │ Answer Relevancy           │ 0.67  │ 0.50      │ N/A                                             │
│        PASS  │ Helpfulness [GEval]        │ 0.90  │ 0.50      │ The Actual Output directly answers the Input    │
│              │                            │       │           │ qu...                                           │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_15                                                                                                │
│  ├──   Input:              Why is RAG useful?                                                                   │
│  │     Actual Output:      RAG is useful for evaluating student progress. It helps teachers know what           │
│  │                         students have mastered and what they need help with. It provides a clear             │
│  │                         understanding of their strengths and weaknesses.                                     │
│  │     Expected Output:    RAG is useful when an AI application needs to answer questions using specific or     │
│  │                         changing information, such as company documents, policies, or knowledge bases.       │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric                     ┃ Score ┃ Threshold ┃ Reason                                          │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        FAIL  │ Answer Correctness [GEval] │ 0.20  │ 0.50      │ The Actual Output contains incorrect facts      │
│              │                            │       │           │ and contradictory information compared to the   │
│              │                            │       │           │ Expected Output. It also introduces new         │
│              │                            │       │           │ information not present in the Expected         │
│              │                            │       │           │ Output.                                         │
│        PASS  │ Answer Relevancy           │ 1.00  │ 0.50      │ N/A                                             │
│        PASS  │ Helpfulness [GEval]        │ 0.80  │ 0.50      │ The Actual Output answer directly addresses     │
│              │                            │       │           │ the...                                          │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_16                                                                                                │
│  ├──   Input:              What is a vector database?                                                           │
│  │     Actual Output:      A vector database is a type of database that stores and manages vectors, which       │
│  │                         are mathematical objects used for dimensionality reduction and similarity            │
│  │                         searches. It's useful for applications like image and text search. Vectors help      │
│  │                         find similarities and patterns in data.                                              │
│  │     Expected Output:    A vector database stores numerical representations called embeddings and allows      │
│  │                         applications to search for information based on semantic similarity.                 │
│  └── Metrics                                                                                                    │

⚠ WARNING: No hyperparameters logged.
» ]8;id=10193160;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 1731.57s | token cost: None)
» Test Results (20 total tests):
   » Pass Rate: 65.0% | Passed: 13 | Failed: 7

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

======================================================================
DEEPEVAL EVALUATION COMPLETED
======================================================================

In [10]:
dir(result)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__class_getitem__',
 '__class_vars__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__fields__',
 '__fields_set__',
 '__format__',
 '__ge__',
 '__get_pydantic_core_schema__',
 '__get_pydantic_json_schema__',
 '__getattr__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__pretty__',
 '__private_attributes__',
 '__pydantic_complete__',
 '__pydantic_computed_fields__',
 '__pydantic_core_schema__',
 '__pydantic_custom_init__',
 '__pydantic_decorators__',
 '__pydantic_extra__',
 '__pydantic_extra_info__',
 '__pydantic_fields__',
 '__pydantic_fields_set__',
 '__pydantic_generic_metadata__',
 '__pydantic_init_subclass__',
 '__pydantic_on_complete__',
 '__pydantic_parent_namespace__',
 '__pydantic_post_init__',
 '__pydantic_private__',
 '__pydantic_root_model__',
 '__pydantic_serializer__',
 '__pydantic_setattr_handlers__',
 '__pydantic_validator__',
 '__reduce__',
 '__reduce_ex__',
 '__replace__',
 '__repr__',
 '__repr_args__',
 '__repr_name__',
 '__repr_recursion__',
 '__repr_str__',
 '__rich_repr__',
 '__setattr__',
 '__setstate__',
 '__signature__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_calculate_keys',
 '_copy_and_set_values',
 '_get_value',
 '_iter',
 '_setattr_handler',
 'confident_link',
 'construct',
 'copy',
 'dict',
 'from_orm',
 'json',
 'model_computed_fields',
 'model_config',
 'model_construct',
 'model_copy',
 'model_dump',
 'model_dump_json',
 'model_extra',
 'model_fields',
 'model_fields_set',
 'model_json_schema',
 'model_parametrized_name',
 'model_post_init',
 'model_rebuild',
 'model_validate',
 'model_validate_json',
 'model_validate_strings',
 'parse_file',
 'parse_obj',
 'parse_raw',
 'schema',
 'schema_json',
 'test_results',
 'test_run_id',
 'update_forward_refs',
 'validate']

In [11]:
result.test_results

[TestResult(name='test_case_0', success=True, metrics_data=[MetricData(name='Answer Correctness [GEval]', threshold=0.5, success=True, score=0.7, reason='The Actual Output contains some minor wording differences, but it accurately conveys the important meaning and facts about AI. However, it introduces some new information, such as AI being a way to make machines smart and helpful, which is not present in the Expected Output.', strict_mode=False, flaky=False, evaluation_model='llama3.1 (Ollama)', error=None, evaluation_cost=0.0, input_tokens=0, output_tokens=0, verbose_logs='Criteria:\n\n    Evaluate whether the generated answer is factually correct\n    compared with the expected teacher answer.\n\n    Give a high score when the important meaning and facts are correct.\n\n    Penalize:\n    - incorrect facts\n    - contradictory information\n    - missing important information\n\n    Minor wording differences should not reduce the score.\n     \n \nEvaluation Steps:\n[\n    "Compare the Actual Output with the Expected Output to identify any factual discrepancies.",\n    "Penalize the Actual Output for any incorrect facts, contradictory information, or missing important information.",\n    "Give a high score if the important meaning and facts in the Actual Output are correct, even if there are minor wording differences.",\n    "Verify that the Actual Output accurately reflects the Expected Output, without introducing new or incorrect information."\n] \n \nRubric:\nNone \n \nScore: 0.7'), MetricData(name='Answer Relevancy', threshold=0.5, success=True, score=1.0, reason=None, strict_mode=False, flaky=False, evaluation_model='llama3.1 (Ollama)', error=None, evaluation_cost=0.0, input_tokens=0, output_tokens=0, verbose_logs='Statements:\n[\n    "AI stands for Artificial Intelligence.",\n    "A computer system can think and learn like a human.",\n    "It uses data and algorithms to make decisions and solve problems.",\n    "AI is a way to make machines smart and helpful."\n] \n \nVerdicts:\n[\n    {\n        "verdict": "yes",\n        "reason": null\n    },\n    {\n        "verdict": "yes",\n        "reason": null\n    },\n    {\n        "verdict": "yes",\n        "reason": null\n    },\n    {\n        "verdict": "yes",\n        "reason": null\n    }\n]'), MetricData(name='Helpfulness [GEval]', threshold=0.5, success=True, score=0.8, reason="The Actual Output answer directly answers the Input question, providing a clear and concise explanation of what AI is. The answer is easy to understand for a beginner student, and it includes relevant information about how AI uses data and algorithms to make decisions and solve problems. However, the answer could be improved by removing unnecessary words and phrases, such as 'a way to make machines smart and helpful', which do not add significant value to the explanation.", strict_mode=False, flaky=False, evaluation_model='llama3.1 (Ollama)', error=None, evaluation_cost=0.0, input_tokens=0, output_tokens=0, verbose_logs='Criteria:\n\n    Evaluate how helpful the generated answer is for a beginner student.\n\n    A helpful answer should:\n\n    1. Directly answer the student\'s question.\n    2. Be easy to understand.\n    3. Provide enough explanation.\n    4. Avoid unnecessary information.\n    5. Help the student understand the concept.\n     \n \nEvaluation Steps:\n[\n    "Compare the Input question to the Actual Output answer to ensure it directly answers the question.",\n    "Assess the clarity of the Actual Output answer and determine if it is easy to understand for a beginner student.",\n    "Evaluate the Actual Output answer for sufficient explanation and relevance to the Input question.",\n    "Check if the Actual Output answer includes unnecessary information and if it helps the student understand the concept."\n] \n \nRubric:\nNone \n \nScore: 0.8')], conversational=False, index=0, multimodal=False, input='What is AI?', actual_output='AI stands for Artificial Intelligence, which is a computer system that can think and learn like a human. It uses data and algorithms to make decisions and solve problems. AI is a way to make machines smart and helpful.', expected_output='AI (Artificial Intelligence) is the ability of computers to perform tasks that normally require human intelligence, such as learning, reasoning, recognizing patterns, and making decisions.', context=None, retrieval_context=None, turns=None, metadata=None, classifications=None, expectations=None),
 TestResult(name='test_case_1', success=False, metrics_data=[MetricData(name='Answer Correctness [GEval]', threshold=0.5, success=False, score=0.2, reason='The Actual Output contains several factual discrepancies and contradictory information compared to the Expected Output. For instance, it incorrectly states that AI can learn and adapt on its own, whereas the Expected Output accurately describes traditional programs as following fixed rules. Additionally, the Actual Output introduces new information about AI improving over time, which is not present in the Expected Output.', strict_mode=False, flaky=False, evaluation_model='llama3.1 (Ollama)', error=None, evaluation_cost=0.0, input_tokens=0, output_tokens=0, verbose_logs='Criteria:\n\n    Evaluate whether the generated answer is factually correct\n    compared with the expected teacher answer.\n\n    Give a high score when the important meaning and facts are correct.\n\n    Penalize:\n    - incorrect facts\n    - contradictory information\n    - missing important information\n\n    Minor wording differences should not reduce the score.\n     \n \nEvaluation Steps:\n[\n    "Compare the Actual Output with the Expected Output to identify any factual discrepancies.",\n    "Penalize the Actual Output for any incorrect facts, contradictory information, or missing important information.",\n    "Give a high score if the important meaning and facts in the Actual Output are correct, even if there are minor wording differences.",\n    "Verify that the Actual Output accurately reflects the Expected Output, without introducing new or incorrect information."\n] \n \nRubric:\nNone \n \nScore: 0.2'), MetricData(name='Answer Relevancy', threshold=0.5, success=True, score=1.0, reason=None, strict_mode=False, flaky=False, evaluation_model='llama3.1 (Ollama)', error=None, evaluation_cost=0.0, input_tokens=0, output_tokens=0, verbose_logs='Statements:\n[\n    "AI can learn and adapt on its own.",\n    "Traditional programming is based on set rules.",\n    "AI uses data and algorithms to make decisions.",\n    "AI can improve over time.",\n    "AI can perform tasks more efficiently."\n] \n \nVerdicts:\n[\n    {\n        "verdict": "yes",\n        "reason": null\n    },\n    {\n        "verdict": "yes",\n        "reason": null\n    },\n    {\n        "verdict": "yes",\n        "reason": null\n    },\n    {\n        "verdict": "yes",\n        "reason": null\n    },\n    {\n        "verdict": "yes",\n        "reason": null\n    }\n]'), MetricData(name='Helpfulness [GEval]', threshold=0.5, success=True, score=0.9, reason="The Actual Output answer directly addresses the Input question, providing a clear explanation of the differences between AI and traditional programming. The answer is easy to understand and includes relevant details about AI's ability to learn and adapt, making it a strong response.", strict_mode=False, flaky=False, evaluation_model='llama3.1 (Ollama)', error=None, evaluation_cost=0.0, input_tokens=0, output_tokens=0, verbose_logs='Criteria:\n\n    Evaluate how helpful the generated answer is for a beginner student.\n\n    A helpful answer should:\n\n    1. Directly answer the student\'s question.\n    2. Be easy to understand.\n    3. Provide enough explanation.\n    4. Avoid unnecessary information.\n    5. Help the student understand the concept.\n     \n \nEvaluation Steps:\n[\n    "Compare the Input question to the Actual Output answer to ensure it directly answers the question.",\n    "Assess the clarity of the Actual Output answer and determine if it is easy to understand for a beginner student.",\n    "Evaluate the Actual Output answer for sufficient explanation and relevance to the Input question.",\n    "Check if the Actual Output answer includes unnecessary information and if it helps the student understand the concept."\n] \n \nRubric:\nNone \n \nScore: 0.9')], conversational=False, index=1, multimodal=False, input='How does AI differ from traditional programming?', actual_output='AI can learn and adapt on its own, unlike traditional programming which is based on set rules. It uses data and algorithms to make decisions. This allows AI to improve over time and perform tasks more efficiently.', expected_output='Traditional programs follow fixed rules written by humans. AI systems can learn patterns from data and use those patterns to make predictions or decisions.', context=None, retrieval_context=None, turns=None, metadata=None, classifications=None, expectations=None),
 TestResult(name='test_case_2', success=True, metrics_data=[MetricData(name='Answer Correctness [GEval]', threshold=0.5, success=True, score=0.8, reason="The Actual Output accurately conveys the important meaning and facts of Machine Learning, including its ability to improve computer performance through data-driven learning. However, it introduces minor wording differences, such as using 'get better at doing tasks' instead of 'learn patterns from data'.", strict_mode=False, flaky=False, evaluation_model='llama3.1 (Ollama)', error=None, evaluation_cost=0.0, input_tokens=0, output_tokens=0, verbose_logs='Criteria:\n\n    Evaluate whether the generated answer is factually correct\n    compared with the expected teacher answer.\n\n    Give a high score when the important meaning and facts are correct.\n\n    Penalize:\n    - incorrect facts\n    - contradictory information\n    - missing important information\n\n    Minor wording differences should not reduce the score.\n     \n \nEvaluation Steps:\n[\n    "Compare the Actual Output with the Expected Output to identify any factual discrepancies.",\n    "Penalize the Actual Output for any incorrect facts, contradictory information, or missing important information.",\n    "Give a high score if the important meaning and facts in the Actual Output are correct, even if there are minor wording differences.",\n    "Verify that the Actual Output accurately reflects the Expected Output, without introducing new or incorrect information."\n] \n \nRubric:\nNone \n \nScore: 0.8'), MetricData(name='Answer Relevancy', threshold=0.5, success=True, score=1.0, reason=None, strict_mode=False, flaky=False, evaluation_model='llama3.1 (Ollama)', error=None, evaluation_cost=0.0, input_tokens=0, output_tokens=0, verbose_logs='Statements:\n[\n    "Machine Learning is a way for computers to get better at doing tasks.",\n    "Computers learn from data and examples.",\n    "It helps computers make predictions and decisions on their own.",\n    "They learn from experience, like a student."\n] \n \nVerdicts:\n[\n    {\n        "verdict": "yes",\n        "reason": null\n    },\n    {\n        "verdict": "yes",\n        "reason": null\n    },\n    {\n        "verdict": "yes",\n        "reason": null\n    },\n    {\n        "verdict": "borderline",\n        "reason": "The statement is somewhat relevant, but it\'s a comparison to a student, which is not directly related to the input."\n    }\n]'), MetricData(name='Helpfulness [GEval]', threshold=0.5, success=True, score=0.8, reason="The Actual Output answer directly addresses the Input question, providing a clear and concise explanation of Machine Learning. The answer is easy to understand for a beginner student, and it includes relevant information about how computers learn from data and examples. However, it could be improved by avoiding unnecessary phrases, such as 'like a student learning from experience', which do not add significant value to the explanation.", strict_mode=False, flaky=False, evaluation_model='llama3.1 (Ollama)', error=None, evaluation_cost=0.0, input_tokens=0, output_tokens=0, verbose_logs='Criteria:\n\n    Evaluate how helpful the generated answer is for a beginner student.\n\n    A helpful answer should:\n\n    1. Directly answer the student\'s question.\n    2. Be easy to understand.\n    3. Provide enough explanation.\n    4. Avoid unnecessary information.\n    5. Help the student understand the concept.\n     \n \nEvaluation Steps:\n[\n    "Compare the Input question to the Actual Output answer to ensure it directly answers the question.",\n    "Assess the clarity of the Actual Output answer and determine if it is easy to understand for a beginner student.",\n    "Evaluate the Actual Output answer for sufficient explanation and relevance to the Input question.",\n    "Check if the Actual Output answer includes unnecessary information and if it helps the student understand the concept."\n] \n \nRubric:\nNone \n \nScore: 0.8')], conversational=False, index=2, multimodal=False, input='What is Machine Learning?', actual_output='Machine Learning is a way for computers to get better at doing tasks without being programmed exactly how to do them. They learn from data and examples, like a student learning from experience. It helps computers make predictions and decisions on their own.', expected_output='Machine Learning is a branch of AI where computers learn patterns from data and use those patterns to make predictions or decisions without being explicitly programmed for every case.', context=None, retrieval_context=None, turns=None, metadata=None, classifications=None, expectations=None),
 TestResult(name='test_case_3', success=True, metrics_data=[MetricData(name='Answer Correctness [GEval]', threshold=0.5, success=True, score=0.8, reason='The Actual Output accurately conveys the important meaning and facts of Deep Learning, including its use in pattern recognition and tasks like image recognition and speech understanding. However, it lacks specific details about the use of neural networks with multiple layers, which is a key aspect of Deep Learning.', strict_mode=False, flaky=False, evaluation_model='llama3.1 (Ollama)', error=None, evaluation_cost=0.0, input_tokens=0, output_tokens=0, verbose_logs='Criteria:\n\n    Evaluate whether the generated answer is factually correct\n    compared with the expected teacher answer.\n\n    Give a high score when the important meaning and facts are correct.\n\n    Penalize:\n    - incorrect facts\n    - contradictory information\n    - missing important information\n\n    Minor wording differences should not reduce the score.\n     \n \nEvaluation Steps:\n[\n    "Compare the Actual Output with the Expected Output to identify any factual discrepancies.",\n    "Penalize the Actual Output for any incorrect facts, contradictory information, or missing important information.",\n    "Give a high score if the important meaning and facts in the Actual Output are correct, even if there are minor wording differences.",\n    "Verify that the Actual Output accurately reflects the Expected Output, without introducing new or incorrect information."\n] \n \nRubric:\nNone \n \nScore: 0.8'), MetricData(name='Answer Relevancy', threshold=0.5, success=True, score=1.0, reason=None, strict_mode=False, flaky=False, evaluation_model='llama3.1 (Ollama)', error=None, evaluation_cost=0.0, input_tokens=0, output_tokens=0, verbose_logs='Statements:\n[\n    "Deep Learning is a type of Machine Learning.",\n    "It uses multiple layers of processing.",\n    "It\'s like a stack of filters.",\n    "The filters help computers recognize patterns in data.",\n    "Computers are really good at tasks like image recognition.",\n    "Computers are really good at tasks like speech understanding."\n] \n \nVerdicts:\n[\n    {\n        "verdict": "yes",\n        "reason": null\n    },\n    {\n        "verdict": "yes",\n        "reason": null\n    },\n    {\n        "verdict": "borderline",\n        "reason": "The analogy is not directly relevant to the question, but it could be used to explain the concept of Deep Learning."\n    },\n    {\n        "verdict": "yes",\n        "reason": null\n    },\n    {\n        "verdict": "yes",\n        "reason": null\n    },\n    {\n        "verdict": "yes",\n        "reason": null\n    }\n]'), MetricData(name='Helpfulness [GEval]', threshold=0.5, success=True, score=0.9, reason="The Actual Output answer directly addresses the Input question, providing a clear and concise explanation of Deep Learning. The answer is easy to understand for a beginner student, and it includes relevant examples to help illustrate the concept. However, the answer could be improved by removing the phrase 'It's like a stack of filters' as it may be considered unnecessary information.", strict_mode=False, flaky=False, evaluation_model='llama3.1 (Ollama)', error=None, evaluation_cost=0.0, input_tokens=0, output_tokens=0, verbose_logs='Criteria:\n\n    Evaluate how helpful the generated answer is for a beginner student.\n\n    A helpful answer should:\n\n    1. Directly answer the student\'s question.\n    2. Be easy to understand.\n    3. Provide enough explanation.\n    4. Avoid unnecessary information.\n    5. Help the student understand the concept.\n     \n \nEvaluation Steps:\n[\n    "Compare the Input question to the Actual Output answer to ensure it directly answers the question.",\n    "Assess the clarity of the Actual Output answer and determine if it is easy to understand for a beginner student.",\n    "Evaluate the Actual Output answer for sufficient explanation and relevance to the Input question.",\n    "Check if the Actual Output answer includes unnecessary information and if it helps the student understand the concept."\n] \n \nRubric:\nNone \n \nScore: 0.9')], conversational=False, index=3, multimodal=False, input='What is Deep Learning?', actual_output="Deep Learning is a type of Machine Learning that uses multiple layers of processing. It's like a stack of filters that help computers recognize patterns in data. This makes computers really good at tasks like image recognition and speech understanding.", expected_output='Deep Learning is a type of Machine Learning that uses neural networks with multiple layers to learn complex patterns from large amounts of data.', context=None, retrieval_context=None, turns=None, metadata=None, classifications=None, expectations=None),

In [12]:
import pandas as pd

from deepeval import evaluate
from deepeval.metrics import AnswerRelevancyMetric, GEval
from deepeval.test_case import LLMTestCase, SingleTurnParams
from deepeval.evaluate import AsyncConfig
from deepeval.models import OllamaModel


# ============================================================
# 1. LOAD DATA
# ============================================================

df = pd.read_csv("ai_teacher_results.csv")

print("Dataset loaded")
print(f"Number of questions: {len(df)}")


# ============================================================
# 2. OLLAMA MODEL
# ============================================================

judge_model = OllamaModel(
    model="llama3.1",
    base_url="http://localhost:11434",
    temperature=0
)

print("Ollama Llama 3.1 judge model configured successfully!")


# ============================================================
# 3. CREATE TEST CASES
# ============================================================

test_cases = []

for _, row in df.iterrows():

    test_case = LLMTestCase(
        input=row["User Query"],
        actual_output=row["GeneratedAnswer"],
        expected_output=row["Teacher Response"]
    )

    test_cases.append(test_case)


print(f"Created {len(test_cases)} test cases")


# ============================================================
# 4. CORRECTNESS METRIC
# ============================================================

correctness = GEval(
    name="Answer Correctness",

    model=judge_model,

    criteria="""
    Evaluate whether the generated answer is factually correct
    compared with the expected teacher answer.

    Give a high score when the important meaning and facts are correct.

    Penalize:
    - incorrect facts
    - contradictory information
    - missing important information

    Minor wording differences should not reduce the score.
    """,

    evaluation_params=[
        SingleTurnParams.ACTUAL_OUTPUT,
        SingleTurnParams.EXPECTED_OUTPUT
    ],

    async_mode=False
)


# ============================================================
# 5. RELEVANCY METRIC
# ============================================================

relevancy = AnswerRelevancyMetric(
    model=judge_model,

    include_reason=False,

    async_mode=False
)


# ============================================================
# 6. HELPFULNESS METRIC
# ============================================================

helpfulness = GEval(
    name="Helpfulness",

    model=judge_model,

    criteria="""
    Evaluate how helpful the generated answer is for a beginner student.

    A helpful answer should:

    1. Directly answer the student's question.
    2. Be easy to understand.
    3. Provide enough explanation.
    4. Avoid unnecessary information.
    5. Help the student understand the concept.

    Give a high score when the answer is clear,
    simple, relevant, and educational.
    """,

    evaluation_params=[
        SingleTurnParams.INPUT,
        SingleTurnParams.ACTUAL_OUTPUT
    ],

    async_mode=False
)


# ============================================================
# 7. RUN DEEPEVAL
# ============================================================

print("\n" + "=" * 70)
print("STARTING DEEPEVAL EVALUATION")
print("=" * 70)

result = evaluate(
    test_cases=test_cases,

    metrics=[
        correctness,
        relevancy,
        helpfulness
    ],

    async_config=AsyncConfig(run_async=False)
)


# ============================================================
# 8. COMPLETED
# ============================================================

print("\n" + "=" * 70)
print("DEEPEVAL EVALUATION COMPLETED")
print("=" * 70)

Dataset loaded
Number of questions: 20
Ollama Llama 3.1 judge model configured successfully!
Created 20 test cases

======================================================================
STARTING DEEPEVAL EVALUATION
======================================================================

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using llama3.1 (Ollama), strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using llama3.1 (Ollama), strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using llama3.1 (Ollama), strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_0 (Passed 3 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_1                                                                                                 │
│  ├──   Input:              How does AI differ from traditional programming?                                     │
│  │     Actual Output:      AI can learn and adapt on its own, unlike traditional programming which is based     │
│  │                         on set rules. It uses data and algorithms to make decisions. This allows AI to       │
│  │                         improve over time and perform tasks more efficiently.                                │
│  │     Expected Output:    Traditional programs follow fixed rules written by humans. AI systems can learn      │
│  │                         patterns from data and use those patterns to make predictions or decisions.          │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric                     ┃ Score ┃ Threshold ┃ Reason                                          │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        FAIL  │ Answer Correctness [GEval] │ 0.20  │ 0.50      │ The Actual Output contains several factual      │
│              │                            │       │           │ discrepancies and contradictory information     │
│              │                            │       │           │ compared to the Expected Output. For            │
│              │                            │       │           │ instance, it incorrectly states that AI can     │
│              │                            │       │           │ learn and adapt on its own, whereas the         │
│              │                            │       │           │ Expected Output accurately describes            │
│              │                            │       │           │ traditional programs as following fixed         │
│              │                            │       │           │ rules. Additionally, the Actual Output          │
│              │                            │       │           │ introduces new information about AI improving   │
│              │                            │       │           │ over time, which is not present in the          │
│              │                            │       │           │ Expected Output.                                │
│        PASS  │ Answer Relevancy           │ 1.00  │ 0.50      │ N/A                                             │
│        PASS  │ Helpfulness [GEval]        │ 0.80  │ 0.50      │ The Actual Output answer directly addresses     │
│              │                            │       │           │ the...                                          │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_2 (Passed 3 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_3 (Passed 3 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_4 (Passed 3 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_5 (Passed 3 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_6 (Passed 3 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_7                                                                                                 │
│  ├──   Input:              What is supervised learning?                                                         │
│  │     Actual Output:      A computer is shown a lot of examples of something, and it has to learn from them    │
│  │                         by making predictions or doing tasks. It's like a student learning from a            │
│  │                         teacher.                                                                             │
│  │     Expected Output:    Supervised learning trains a model using examples that already have known            │
│  │                         answers, such as customer information paired with whether the customer left the      │
│  │                         company.                                                                             │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric                     ┃ Score ┃ Threshold ┃ Reason                                          │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        FAIL  │ Answer Correctness [GEval] │ 0.40  │ 0.50      │ The Actual Output contains some correct         │
│              │                            │       │           │ concepts, such as learning from examples, but   │
│              │                            │       │           │ it introduces new and incorrect information,    │
│              │                            │       │           │ like comparing it to a student learning from    │
│              │                            │       │           │ a teacher. It also lacks the specific details   │
│              │                            │       │           │ about supervised learning, like customer        │
│              │                            │       │           │ information paired with known answers.          │
│        PASS  │ Answer Relevancy           │ 1.00  │ 0.50      │ N/A                                             │
│        PASS  │ Helpfulness [GEval]        │ 0.80  │ 0.50      │ The Actual Output answer directly addresses     │
│              │                            │       │           │ the...                                          │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_8 (Passed 3 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_9 (Passed 3 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_10 (Passed 3 metrics)                                                                              │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_11 (Passed 3 metrics)                                                                              │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_12                                                                                                │
│  ├──   Input:              What is a prompt?                                                                    │
│  │     Actual Output:      A prompt is a question or a starting point for writing or discussion. It helps       │
│  │                         guide the thoughts and ideas. It's like a map to the solution or answer.             │
│  │     Expected Output:    A prompt is the instruction or input given to an AI model to tell it what you        │
│  │                         want it to do, such as explain a concept, write code, or summarize text.             │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric                     ┃ Score ┃ Threshold ┃ Reason                                          │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        FAIL  │ Answer Correctness [GEval] │ 0.40  │ 0.50      │ The Actual Output contains some correct         │
│              │                            │       │           │ facts, but it also introduces new and           │
│              │                            │       │           │ incorrect information, such as comparing a      │
│              │                            │       │           │ prompt to a map. The important meaning and      │
│              │                            │       │           │ facts in the Actual Output are not entirely     │
│              │                            │       │           │ correct.                                        │
│        PASS  │ Answer Relevancy           │ 1.00  │ 0.50      │ N/A                                             │
│        PASS  │ Helpfulness [GEval]        │ 0.80  │ 0.50      │ The Actual Output answer directly answers the   │
│              │                            │       │           │ I...                                            │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_13 (Passed 3 metrics)                                                                              │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_14                                                                                                │
│  ├──   Input:              What is RAG?                                                                         │
│  │     Actual Output:      RAG is a rating system used to track progress and achievements in various            │
│  │                         subjects or activities. It stands for Red, Amber, and Green, which indicate          │
│  │                         different levels of performance. Red means you need to work harder, Amber means      │
│  │                         you're making progress, and Green means you're doing well.                           │
│  │     Expected Output:    RAG stands for Retrieval-Augmented Generation. It retrieves relevant information     │
│  │                         from external data sources and provides that information to an LLM before            │
│  │                         generating an answer.                                                                │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric                     ┃ Score ┃ Threshold ┃ Reason                                          │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        FAIL  │ Answer Correctness [GEval] │ 0.00  │ 0.50      │ The Actual Output contains incorrect facts      │
│              │                            │       │           │ and contradictory information. It describes     │
│              │                            │       │           │ RAG as a rating system, whereas the Expected    │
│              │                            │       │           │ Output correctly identifies it as a             │
│              │                            │       │           │ retrieval-augmented generation system.          │
│              │                            │       │           │ Additionally, the Actual Output introduces      │
│              │                            │       │           │ new information about the meaning of Red,       │
│              │                            │       │           │ Amber, and Green, which is not present in the   │
│              │                            │       │           │ Expected Output.                                │
│        PASS  │ Answer Relevancy           │ 0.67  │ 0.50      │ N/A                                             │
│        PASS  │ Helpfulness [GEval]        │ 0.80  │ 0.50      │ The Actual Output directly answers the Input    │
│              │                            │       │           │ qu...                                           │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_15                                                                                                │
│  ├──   Input:              Why is RAG useful?                                                                   │
│  │     Actual Output:      RAG is useful for evaluating student progress. It helps teachers know what           │
│  │                         students have mastered and what they need help with. It provides a clear             │
│  │                         understanding of their strengths and weaknesses.                                     │
│  │     Expected Output:    RAG is useful when an AI application needs to answer questions using specific or     │
│  │                         changing information, such as company documents, policies, or knowledge bases.       │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric                     ┃ Score ┃ Threshold ┃ Reason                                          │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        FAIL  │ Answer Correctness [GEval] │ 0.20  │ 0.50      │ The Actual Output contains incorrect facts      │
│              │                            │       │           │ and contradictory information compared to the   │
│              │                            │       │           │ Expected Output. It also introduces new         │
│              │                            │       │           │ information not present in the Expected         │
│              │                            │       │           │ Output.                                         │
│        PASS  │ Answer Relevancy           │ 1.00  │ 0.50      │ N/A                                             │
│        PASS  │ Helpfulness [GEval]        │ 0.80  │ 0.50      │ The Actual Output answer directly addresses     │
│              │                            │       │           │ the...                                          │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_16                                                                                                │
│  ├──   Input:              What is a vector database?                                                           │
│  │     Actual Output:      A vector database is a type of database that stores and manages vectors, which       │
│  │                         are mathematical objects used for dimensionality reduction and similarity            │
│  │                         searches. It's useful for applications like image and text search. Vectors help      │
│  │                         find similarities and patterns in data.                                              │
│  │     Expected Output:    A vector database stores numerical representations called embeddings and allows      │
│  │                         applications to search for information based on semantic similarity.                 │
│  └── Metrics                                                                                                    │

⚠ WARNING: No hyperparameters logged.
» ]8;id=10193162;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 1655.47s | token cost: None)
» Test Results (20 total tests):
   » Pass Rate: 65.0% | Passed: 13 | Failed: 7

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

======================================================================
DEEPEVAL EVALUATION COMPLETED
======================================================================

In [13]:

for i, test_result in enumerate(result.test_results):

    metrics_data = test_result.metrics_data

    df.loc[i, "AnswerCorrectness"] = metrics_data[0].score
    df.loc[i, "AnswerRelevancy"] = metrics_data[1].score
    df.loc[i, "Helpfulness"] = metrics_data[2].score


# ============================================================
# 3. CALCULATE OVERALL ANSWER QUALITY
# ============================================================

df["AnswerQuality"] = (
    df["AnswerCorrectness"]
    + df["AnswerRelevancy"]
    + df["Helpfulness"]
) / 3


# ============================================================
# 4. ROUND SCORES
# ============================================================

metric_columns = [
    "AnswerCorrectness",
    "AnswerRelevancy",
    "Helpfulness",
    "AnswerQuality"
]

df[metric_columns] = df[metric_columns].round(3)


# ============================================================
# 5. AVERAGES
# ============================================================

average_correctness = df["AnswerCorrectness"].mean()
average_relevancy = df["AnswerRelevancy"].mean()
average_helpfulness = df["Helpfulness"].mean()
average_quality = df["AnswerQuality"].mean()


# ============================================================
# 6. QUESTION-WISE RESULTS
# ============================================================

print("\n")
print("=" * 120)
print("                         AI TEACHER ANSWER QUALITY")
print("=" * 120)

display_df = df[
    [
        "User Query",
        "AnswerCorrectness",
        "AnswerRelevancy",
        "Helpfulness",
        "AnswerQuality"
    ]
]


# ============================================================
# 8. SAVE FINAL RESULT
# ============================================================

df.to_csv(
    "ai_teacher_evaluation.csv",
    index=False,
    encoding="utf-8-sig"
)

========================================================================================================================
                         AI TEACHER ANSWER QUALITY
========================================================================================================================

In [14]:
df

,User Query,Teacher Response,GeneratedAnswer,AnswerCorrectness,AnswerRelevancy,Helpfulness,AnswerQuality
0,What is AI?,AI (Artificial Intelligence) is the ability of...,"AI stands for Artificial Intelligence, which i...",0.7,1.000,0.8,0.833
1,How does AI differ from traditional programming?,Traditional programs follow fixed rules writte...,"AI can learn and adapt on its own, unlike trad...",0.2,1.000,0.8,0.667
2,What is Machine Learning?,Machine Learning is a branch of AI where compu...,Machine Learning is a way for computers to get...,0.8,1.000,0.8,0.867
3,What is Deep Learning?,Deep Learning is a type of Machine Learning th...,Deep Learning is a type of Machine Learning th...,0.8,1.000,0.8,0.867
4,"What is the difference between AI, ML, and Dee...",AI is the broad field of making machines intel...,Artificial Intelligence (AI) is the overall id...,0.9,1.000,0.8,0.900
5,What is training data?,Training data is the data used to teach a Mach...,Training data is the information used to teach...,0.7,1.000,0.8,0.833
6,What is a Machine Learning model?,A Machine Learning model is a mathematical sys...,A Machine Learning model is a set of instructi...,0.6,1.000,0.8,0.800
7,What is supervised learning?,Supervised learning trains a model using examp...,A computer is shown a lot of examples of somet...,0.4,1.000,0.8,0.733
8,What is unsupervised learning?,Unsupervised learning works with data that doe...,Unsupervised learning is a type of machine lea...,0.9,1.000,0.8,0.900
9,What is reinforcement learning?,Reinforcement learning teaches an agent throug...,"The computer learns by trial and error, making...",0.7,1.000,0.8,0.833
10,What is an LLM?,"An LLM, or Large Language Model, is an AI mode...",An LLM is a type of computer program that uses...,0.8,0.800,0.9,0.833
11,What is Generative AI?,Generative AI is AI that can create new conten...,"Generative AI creates new content, like images...",0.8,0.857,0.8,0.819
12,What is a prompt?,A prompt is the instruction or input given to ...,A prompt is a question or a starting point for...,0.4,1.000,0.8,0.733
13,What is Prompt Engineering?,Prompt Engineering is the practice of designin...,Prompt Engineering is the process of refining ...,0.8,0.667,0.8,0.756
14,What is RAG?,RAG stands for Retrieval-Augmented Generation....,RAG is a rating system used to track progress ...,0.0,0.667,0.8,0.489
15,Why is RAG useful?,RAG is useful when an AI application needs to ...,RAG is useful for evaluating student progress....,0.2,1.000,0.8,0.667
16,What is a vector database?,A vector database stores numerical representat...,A vector database is a type of database that s...,0.4,1.000,0.9,0.767
17,What are embeddings?,Embeddings are numerical representations of te...,Embeddings are like maps that help computers u...,0.7,1.000,0.8,0.833
18,What is an AI Agent?,An AI Agent is a system that can understand a ...,An AI Agent is a program that can make decisio...,0.7,1.000,0.8,0.833
19,How can AI be used in education?,AI can support education by explaining concept...,AI can help teachers with grading and lesson p...,0.4,1.000,0.8,0.733

In [15]:
average_result=pd.DataFrame(columns=["average_correctness","average_relevancy","average_helpfulness","average_quality"],
                            data=[[average_correctness,average_relevancy,average_helpfulness,average_quality]])

In [16]:
average_result

,average_correctness,average_relevancy,average_helpfulness,average_quality
0,0.595,0.94955,0.81,0.7848