# STAGE 1 - IMPORTS AND CONFIGURATION

In [1]:
import os
import time
import asyncio
import logging
import numpy as np
import pandas as pd
import nltk

from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import FAISS
# Ollama integrations
from langchain_ollama import ChatOllama, OllamaEmbeddings

from langchain_core.prompts import ChatPromptTemplate

from bert_score import BERTScorer
from rouge_score import rouge_scorer
from nltk.translate.meteor_score import meteor_score

from deepeval.test_case import LLMTestCase, LLMTestCaseParams

from deepeval.metrics import (
    GEval,
    AnswerRelevancyMetric,
    ContextualPrecisionMetric,
    ContextualRecallMetric,
    FaithfulnessMetric
)

from deepeval.models import OllamaModel


# ============================================================
# 1. CONFIGURATION
# ============================================================

MODEL = "llama3.1"

# Local Ollama server
OLLAMA_BASE_URL = "http://localhost:11434"

# Local embeddings
EMBEDDING_MODEL = "nomic-embed-text"


# ============================================================
# 2. FILE CONFIGURATION
# ============================================================

INPUT_CSV = "ai_teacher_20_questions.csv"
PDF_FILE = "HopeAI_Teaching.pdf"
OUTPUT_CSV = "RAG_LLM_FINAL_EVALUATION_OLLAMA.csv"


# ============================================================
# 3. LOGGING
# ============================================================

logging.getLogger("deepeval").setLevel(logging.CRITICAL)
logging.getLogger("transformers").setLevel(logging.ERROR)


# ============================================================
# 4. NLTK
# ============================================================

nltk.download("wordnet", quiet=True)
nltk.download("omw-1.4", quiet=True)


# ============================================================
# 5. LOAD DATA
# ============================================================

df = pd.read_csv(INPUT_CSV)

required_columns = [
    "User Query",
    "Teacher Response"
]

missing = set(required_columns) - set(df.columns)

if missing:
    raise ValueError(
        f"Missing CSV columns: {missing}"
    )

df = df.dropna(
    subset=required_columns
).reset_index(drop=True)

df["User Query"] = (
    df["User Query"]
    .astype(str)
    .str.strip()
)

df["Teacher Response"] = (
    df["Teacher Response"]
    .astype(str)
    .str.strip()
)

print(f"Questions loaded: {len(df)}")


# ============================================================
# 6. OLLAMA LLM
# ============================================================

llm = ChatOllama(
    model=MODEL,
    base_url=OLLAMA_BASE_URL,
    temperature=0
)

print("Ollama Llama 3.1 loaded!")


# ============================================================
# 7. OLLAMA EMBEDDINGS
# ============================================================

embeddings = OllamaEmbeddings(
    model=EMBEDDING_MODEL,
    base_url=OLLAMA_BASE_URL
)

print("Ollama embedding model loaded!")

C:\Users\manju\AppData\Local\Temp\ipykernel_13960\782346669.py:9: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.document_loaders import PyPDFLoader
C:\Users\manju\AppData\Local\Temp\ipykernel_13960\782346669.py:21: DeprecationWarning: 'LLMTestCaseParams' is deprecated and will be removed in a future release. Use 'SingleTurnParams' instead.
  from deepeval.test_case import LLMTestCase, LLMTestCaseParams

Questions loaded: 20
Ollama Llama 3.1 loaded!
Ollama embedding model loaded!

# STAGE 2 - RAG PIPELINE

In [2]:
PDF_FILE = "AI_Teaching.pdf"

# Load PDF
documents = PyPDFLoader(PDF_FILE).load()

# Chunk documents
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=150
)

chunks = text_splitter.split_documents(documents)

# Ollama embeddings
embeddings = OllamaEmbeddings(
    model="nomic-embed-text",
    base_url="http://localhost:11434"
)

# FAISS
vectorstore = FAISS.from_documents(
    chunks,
    embeddings
)

retriever = vectorstore.as_retriever(
    search_kwargs={"k": 3}
)

# Ollama LLM
llm = ChatOllama(
    model="llama3.1",
    base_url="http://localhost:11434",
    temperature=0
)

print("PDF pages loaded:", len(documents))
print("Chunks created:", len(chunks))
print("FAISS vector store ready.")
print("Ollama LLM ready.")

PDF pages loaded: 6
Chunks created: 14
FAISS vector store ready.
Ollama LLM ready.

# STAGE 3 - DEFINE EVALUATION METRICS

In [3]:
# ============================================================
# SIMILARITY METRICS
# ============================================================

bert_scorer = BERTScorer(
    lang="en",
    rescale_with_baseline=False
)

rouge = rouge_scorer.RougeScorer(
    ["rouge1", "rouge2", "rougeL"],
    use_stemmer=True
)


# ============================================================
# OLLAMA EVALUATION MODEL
# ============================================================

EVALUATION_MODEL = "llama3.1"

judge_model = OllamaModel(
    model=EVALUATION_MODEL,
    base_url="http://localhost:11434",
    temperature=0
)


# ============================================================
# ANSWER CORRECTNESS
# ============================================================

correctness_metric = GEval(
    name="Answer Correctness",
    model=judge_model,
    criteria="""
    Compare the generated answer with the reference answer.

    Evaluate:
    - factual accuracy
    - important information
    - contradictions
    - completeness

    Ignore minor wording differences.
    """,
    evaluation_params=[
        LLMTestCaseParams.ACTUAL_OUTPUT,
        LLMTestCaseParams.EXPECTED_OUTPUT
    ],
    async_mode=False
)


# ============================================================
# HELPFULNESS
# ============================================================

helpfulness_metric = GEval(
    name="Helpfulness",
    model=judge_model,
    criteria="""
    Evaluate whether the answer:
    - directly addresses the question
    - is easy for a beginner to understand
    - provides a clear explanation
    - is useful to the learner
    - avoids unnecessary information
    """,
    evaluation_params=[
        LLMTestCaseParams.INPUT,
        LLMTestCaseParams.ACTUAL_OUTPUT
    ],
    async_mode=False
)


# ============================================================
# ANSWER RELEVANCY
# ============================================================

answer_relevancy_metric = AnswerRelevancyMetric(
    model=judge_model,
    include_reason=False,
    async_mode=False
)


# ============================================================
# RAG GEVAL
# ============================================================

rag_geval_metric = GEval(
    name="RAG Correctness",
    model=judge_model,
    criteria="""
    Evaluate whether the generated answer is:

    1. Factually correct
    2. Consistent with the reference answer
    3. Complete enough to answer the question
    4. Free from important contradictions

    Ignore minor differences in wording.
    """,
    evaluation_params=[
        LLMTestCaseParams.ACTUAL_OUTPUT,
        LLMTestCaseParams.EXPECTED_OUTPUT
    ],
    async_mode=False
)


# ============================================================
# RETRIEVAL / RAG METRICS
# ============================================================

context_precision_metric = ContextualPrecisionMetric(
    model=judge_model
)

context_recall_metric = ContextualRecallMetric(
    model=judge_model
)

faithfulness_metric = FaithfulnessMetric(
    model=judge_model
)

rag_answer_relevancy_metric = AnswerRelevancyMetric(
    model=judge_model,
    include_reason=False,
    async_mode=False
)


print("All Ollama evaluation metrics initialized.")

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

All Ollama evaluation metrics initialized.

# STAGE 4 - INPUT QUERIES, GENERATE ANSWERS AND CALCULATE OPERATIONAL METRICS

In [4]:
# ============================================================
# DEFINE RETRIEVAL FUNCTION
# ============================================================

def get_context(query):
    retrieved_docs = retriever.invoke(query)

    retrieval_context = [
        doc.page_content
        for doc in retrieved_docs
    ]

    context = "\n\n".join(retrieval_context)

    return context, retrieval_context


print("SUCCESS: get_context() is defined.")

SUCCESS: get_context() is defined.

In [5]:
# ============================================================
# TEST get_context()
# ============================================================

test_query = "What is AI?"

context, retrieval_context = get_context(test_query)

print("Number of retrieved documents:", len(retrieval_context))
print("\nContext length:", len(context))

for i, ctx in enumerate(retrieval_context, 1):
    print(f"\n--- Retrieved Context {i} ---")
    print(ctx[:500])

Number of retrieved documents: 3

Context length: 2831

--- Retrieved Context 1 ---
AI Teaching: Principles, Methods, and Classroom
 Practice
A practical reference document for an AI Teacher and Retrieval-Augmented Generation (RAG) evaluation
project.
1. Introduction to AI in Education
What is Artificial Intelligence?
Artificial Intelligence (AI) refers to computer systems that can perform tasks that normally require human
intelligence. These tasks include understanding language, recognizing patterns, generating text, solving
problems, making predictions, and assisting with dec

--- Retrieved Context 2 ---
The AI teacher should explain RAG using the retrieved material. If the student asks for information that is not
present in the document, the AI should clearly state that the information could not be found in the provided
document rather than inventing an answer.
13. Key Terms
Artificial Intelligence
Computer systems designed to perform tasks associated with human intelligence.
Generative AI
AI that creates new content such as text, images, or code.
LLM
Large Language Model capable of processing

--- Retrieved Context 3 ---
Answer correctness compares an AI-generated response with a trusted reference answer or reliable
evidence.
8. Operational Metrics
Latency
Latency is the amount of time required to produce an AI response. Lower latency generally provides a better
interactive learning experience.
Token Usage
Tokens are units of text processed by a language model. Token counts can be used to measure input and
output processing.
Cost
Cloud AI services may charge according to input and output token usage. Local model

In [6]:
from langchain_core.prompts import ChatPromptTemplate

# ============================================================
# RAG PROMPT
# ============================================================

rag_prompt = ChatPromptTemplate.from_template("""
You are an AI teacher.

Answer the student's question using only the information
provided in the retrieved context.

Rules:
- Give a clear and accurate explanation.
- Keep the explanation appropriate for a learner.
- Do not invent information that is not supported by the context.
- If the answer cannot be found in the context, say:
  "The information could not be found in the provided document."

Retrieved Context:
{context}

Student Question:
{question}

Answer:
""")

print("SUCCESS: rag_prompt is defined.")

SUCCESS: rag_prompt is defined.

In [7]:
# ============================================================
# TEST RAG GENERATION
# ============================================================

test_query = "What is AI?"

context, retrieval_context = get_context(test_query)

prompt_value = rag_prompt.invoke({
    "context": context,
    "question": test_query
})

response = llm.invoke(prompt_value)

print("Question:")
print(test_query)

print("\nGenerated Answer:")
print(response.content)

print("\nResponse Metadata:")
print(response.response_metadata)

Question:
What is AI?

Generated Answer:
According to the retrieved context, Artificial Intelligence (AI) is defined as:

"Artificial Intelligence (AI) refers to computer systems that can perform tasks that normally require human intelligence. These tasks include understanding language, recognizing patterns, generating text, solving problems, making predictions, and assisting with decisions."

So, AI is essentially computer systems that can perform tasks that are typically done by humans, using their intelligence.

Response Metadata:
{'model': 'llama3.1', 'created_at': '2026-10-14T11:44:39.1267013Z', 'done': True, 'done_reason': 'stop', 'total_duration': 56020610100, 'load_duration': 15155512000, 'prompt_eval_count': 626, 'prompt_eval_duration': 26706121000, 'eval_count': 82, 'eval_duration': 14100189000, 'logprobs': None, 'model_name': 'llama3.1', 'model_provider': 'ollama'}

In [8]:
from tqdm.auto import tqdm
import time
import numpy as np
import pandas as pd

results = []

for _, row in tqdm(
    df.iterrows(),
    total=len(df),
    desc="RAG generation"
):

    query = row["User Query"]
    reference = row["Teacher Response"]

    try:

        total_start = time.perf_counter()

        # ====================================================
        # RETRIEVAL
        # ====================================================

        start = time.perf_counter()

        context, retrieval_context = get_context(query)

        retrieval_latency = time.perf_counter() - start


        # ====================================================
        # GENERATION
        # ====================================================

        prompt_value = rag_prompt.invoke({
            "context": context,
            "question": query
        })

        start = time.perf_counter()

        response = llm.invoke(prompt_value)

        generation_latency = time.perf_counter() - start

        total_latency = time.perf_counter() - total_start

        generated = response.content.strip()


        # ====================================================
        # OLLAMA TOKEN USAGE
        # ====================================================

        metadata = getattr(
            response,
            "response_metadata",
            {}
        )

        input_tokens = metadata.get(
            "prompt_eval_count",
            0
        )

        output_tokens = metadata.get(
            "eval_count",
            0
        )

        total_tokens = (
            input_tokens + output_tokens
        )


        # ====================================================
        # OLLAMA TIMING
        # ====================================================

        ollama_total_duration = metadata.get(
            "total_duration",
            0
        )

        ollama_load_duration = metadata.get(
            "load_duration",
            0
        )

        ollama_prompt_eval_duration = metadata.get(
            "prompt_eval_duration",
            0
        )

        ollama_eval_duration = metadata.get(
            "eval_duration",
            0
        )


        # ====================================================
        # LOCAL COST
        # ====================================================

        input_cost = 0.0
        output_cost = 0.0
        total_cost = 0.0


        # ====================================================
        # SAVE RESULTS
        # ====================================================

        results.append({

            "User Query": query,

            "Teacher Response": reference,

            "GeneratedAnswer": generated,

            "RetrievedContext": retrieval_context,

            "RetrievalLatency": retrieval_latency,

            "GenerationLatency": generation_latency,

            "Latency": total_latency,

            "InputTokens": input_tokens,

            "OutputTokens": output_tokens,

            "TotalTokens": total_tokens,

            "OllamaTotalDuration": ollama_total_duration,

            "OllamaLoadDuration": ollama_load_duration,

            "OllamaPromptEvalDuration": ollama_prompt_eval_duration,

            "OllamaEvalDuration": ollama_eval_duration,

            "InputCost": input_cost,

            "OutputCost": output_cost,

            "TotalCost": total_cost

        })


    except Exception as e:

        print(
            f"\nError processing query: {query}\n"
            f"{type(e).__name__}: {e}"
        )

        results.append({

            "User Query": query,

            "Teacher Response": reference,

            "GeneratedAnswer": "",

            "RetrievedContext": [],

            "RetrievalLatency": np.nan,

            "GenerationLatency": np.nan,

            "Latency": np.nan,

            "InputTokens": np.nan,

            "OutputTokens": np.nan,

            "TotalTokens": np.nan,

            "OllamaTotalDuration": np.nan,

            "OllamaLoadDuration": np.nan,

            "OllamaPromptEvalDuration": np.nan,

            "OllamaEvalDuration": np.nan,

            "InputCost": np.nan,

            "OutputCost": np.nan,

            "TotalCost": np.nan

        })


# ============================================================
# CREATE DATAFRAME
# ============================================================

results_df = pd.DataFrame(results)

successful = results_df["GeneratedAnswer"].ne("").sum()

print(f"\nCompleted: {successful}/{len(results_df)}")

display(results_df)

RAG generation:   0%|          | 0/20 [00:00<?, ?it/s]

Completed: 20/20

,User Query,Teacher Response,GeneratedAnswer,RetrievedContext,RetrievalLatency,GenerationLatency,Latency,InputTokens,OutputTokens,TotalTokens,OllamaTotalDuration,OllamaLoadDuration,OllamaPromptEvalDuration,OllamaEvalDuration,InputCost,OutputCost,TotalCost
0,What is AI?,AI (Artificial Intelligence) is the ability of...,"According to the retrieved context, Artificial...","[AI Teaching: Principles, Methods, and Classro...",2.161472,16.745282,18.909780,626,79,705,14704900400,52446300,247984000,14396202000,0.0,0.0,0.0
1,How does AI differ from traditional programming?,Traditional programs follow fixed rules writte...,The information could not be found in the prov...,"[AI Teaching: Principles, Methods, and Classro...",2.112385,19.942862,22.056342,548,34,582,19940386000,33830200,12530799000,7262712000,0.0,0.0,0.0
2,What is Machine Learning?,Machine Learning is a branch of AI where compu...,The information could not be found in the prov...,[Generative AI\nGenerative AI is a type of art...,2.105053,25.862374,27.968485,638,12,650,25854451800,28852000,23921622000,1819712000,0.0,0.0,0.0
3,What is Deep Learning?,Deep Learning is a type of Machine Learning th...,The information could not be found in the prov...,[Generative AI\nGenerative AI is a type of art...,2.108819,2.629174,4.738691,638,12,650,2625676400,20071100,777631000,1819484000,0.0,0.0,0.0
4,"What is the difference between AI, ML, and Dee...",AI is the broad field of making machines intel...,The information could not be found in the prov...,[Generative AI\nGenerative AI is a type of art...,0.067245,12.042182,12.109831,646,67,713,12039507700,13067400,1087701000,10931612000,0.0,0.0,0.0
5,What is training data?,Training data is the data used to teach a Mach...,The information could not be found in the prov...,[Generative AI\nGenerative AI is a type of art...,2.131822,15.834536,17.966827,593,12,605,15831938000,26795700,13746576000,1941645000,0.0,0.0,0.0
6,What is a Machine Learning model?,A Machine Learning model is a mathematical sys...,The information could not be found in the prov...,[Generative AI\nGenerative AI is a type of art...,2.113730,2.717188,4.831309,640,12,652,2712276000,19514900,853267000,1784431000,0.0,0.0,0.0
7,What is supervised learning?,Supervised learning trains a model using examp...,The information could not be found in the prov...,[Generative AI\nGenerative AI is a type of art...,0.041955,18.225262,18.267614,638,12,650,18222658200,14414200,16233756000,1940446000,0.0,0.0,0.0
8,What is unsupervised learning?,Unsupervised learning works with data that doe...,The information could not be found in the prov...,"[AI Teaching: Principles, Methods, and Classro...",2.139604,16.300255,18.440918,558,12,570,16295673400,42164500,14273178000,1876447000,0.0,0.0,0.0
9,What is reinforcement learning?,Reinforcement learning teaches an agent throug...,The information could not be found in the prov...,"[AI Teaching: Principles, Methods, and Classro...",2.116977,7.546395,9.663943,549,12,561,7543737100,26161000,5622065000,1835409000,0.0,0.0,0.0
10,What is an LLM?,"An LLM, or Large Language Model, is an AI mode...","According to the retrieved context, a Large La...",[Generative AI\nGenerative AI is a type of art...,2.116133,17.276896,19.393814,603,59,662,17271152200,15188500,7051169000,10136966000,0.0,0.0,0.0
11,What is Generative AI?,Generative AI is AI that can create new conten...,Generative AI is a type of artificial intellig...,[Generative AI\nGenerative AI is a type of art...,2.110628,14.247171,16.358318,550,42,592,14245036300,27847200,6530060000,7627075000,0.0,0.0,0.0
12,What is a prompt?,A prompt is the instruction or input given to ...,A prompt is an instruction or question given t...,[A prompt is an instruction or question given ...,2.101228,29.617154,31.719303,619,27,646,29614322300,21155500,25110272000,4373058000,0.0,0.0,0.0
13,What is Prompt Engineering?,Prompt Engineering is the practice of designin...,The information could not be found in the prov...,[A prompt is an instruction or question given ...,2.112884,12.135181,14.248462,666,12,678,12132245300,14159900,10236332000,1872725000,0.0,0.0,0.0
14,What is RAG?,RAG stands for Retrieval-Augmented Generation....,RAG stands for Retrieval-Augmented Generation....,[specified knowledge source.\nRAG Process\nA t...,2.092453,31.853820,33.946678,609,44,653,31851828900,24189700,24346645000,7437389000,0.0,0.0,0.0
15,Why is RAG useful?,RAG is useful when an AI application needs to ...,RAG is useful because it allows an AI model to...,[specified knowledge source.\nRAG Process\nA t...,2.079735,11.703259,13.783391,610,66,676,11700903800,13947700,977398000,10703879000,0.0,0.0,0.0
16,What is a vector database?,A vector database stores numerical representat...,A vector database is a system used to store an...,[specified knowledge source.\nRAG Process\nA t...,2.136547,6.433357,8.570521,483,16,499,6431383700,14986700,4081366000,2327956000,0.0,0.0,0.0
17,What are embeddings?,Embeddings are numerical representations of te...,"According to the provided context, an embeddin...",[specified knowledge source.\nRAG Process\nA t...,2.093934,15.733742,17.828064,601,39,640,15730768300,35144000,9463319000,6226494000,0.0,0.0,0.0
18,What is an AI Agent?,An AI Agent is a system that can understand a ...,The information could not be found in the prov...,"[AI Teaching: Principles, Methods, and Classro...",2.069437,19.568746,21.638585,636,12,648,19563681400,15636600,17637730000,1855046000,0.0,0.0,0.0
19,How can AI be used in education?,AI can support education by explaining concept...,"According to the context, AI can be used in ed...","[AI Teaching: Principles, Methods, and Classro...",2.099355,25.493453,27.593660,549,70,619,25489878200,41124600,13856669000,11530445000,0.0,0.0,0.0

# STAGE 5 - LLM EVALUATION - ANSWER QUALITY

In [9]:
import json
import re

def extract_json(text):

    text = text.strip()

    # Remove markdown code fences if Ollama returns them
    text = re.sub(
        r"```json\s*",
        "",
        text,
        flags=re.IGNORECASE
    )

    text = re.sub(
        r"```\s*$",
        "",
        text
    )

    # Extract JSON object
    match = re.search(
        r"\{.*\}",
        text,
        flags=re.DOTALL
    )

    if not match:
        raise ValueError("No valid JSON found in Ollama response.")

    return json.loads(match.group())


# ============================================
# LLM EVALUATION - ANSWER QUALITY
# ============================================

quality_scores = []

for _, row in tqdm(
    results_df.iterrows(),
    total=len(results_df),
    desc="Answer quality"
):

    query = row["User Query"]
    generated = row["GeneratedAnswer"]
    reference = row["Teacher Response"]

    if not generated:
        quality_scores.append([np.nan] * 3)
        continue

    prompt = f"""
You are an AI teacher evaluator.

Evaluate the generated answer based on the question
and reference answer.

Question:
{query}

Reference Answer:
{reference}

Generated Answer:
{generated}

Give scores from 0 to 1 for:

1. Correctness - factual accuracy
2. Answer Relevancy - directly answers the question
3. Helpfulness - clear and useful for the learner

Return ONLY valid JSON:

{{
    "correctness": 0.0,
    "answer_relevancy": 0.0,
    "helpfulness": 0.0
}}

Scores must be between 0 and 1.
"""

    try:

        response = llm.invoke(prompt)

        scores = extract_json(response.content)

        correctness = float(
            scores["correctness"]
        )

        relevancy = float(
            scores["answer_relevancy"]
        )

        helpfulness = float(
            scores["helpfulness"]
        )

        # Keep scores between 0 and 1
        correctness = max(
            0.0,
            min(1.0, correctness)
        )

        relevancy = max(
            0.0,
            min(1.0, relevancy)
        )

        helpfulness = max(
            0.0,
            min(1.0, helpfulness)
        )

        quality_scores.append([
            correctness,
            relevancy,
            helpfulness
        ])

    except Exception as e:

        print(
            f"Evaluation error: {e}"
        )

        quality_scores.append(
            [np.nan] * 3
        )


results_df[
    [
        "AnswerCorrectness",
        "AnswerRelevancy",
        "Helpfulness"
    ]
] = pd.DataFrame(
    quality_scores,
    index=results_df.index
)


results_df["AnswerQuality"] = results_df[
    [
        "AnswerCorrectness",
        "AnswerRelevancy",
        "Helpfulness"
    ]
].mean(axis=1)


display(
    results_df[
        [
            "User Query",
            "AnswerCorrectness",
            "AnswerRelevancy",
            "Helpfulness",
            "AnswerQuality"
        ]
    ]
)

Answer quality:   0%|          | 0/20 [00:00<?, ?it/s]

,User Query,AnswerCorrectness,AnswerRelevancy,Helpfulness,AnswerQuality
0,What is AI?,0.8,0.9,0.8,0.833333
1,How does AI differ from traditional programming?,0.0,0.0,0.0,0.000000
2,What is Machine Learning?,0.0,0.0,0.0,0.000000
3,What is Deep Learning?,0.0,0.0,0.0,0.000000
4,"What is the difference between AI, ML, and Dee...",0.0,0.0,0.0,0.000000
5,What is training data?,0.0,0.0,0.0,0.000000
6,What is a Machine Learning model?,0.0,0.0,0.0,0.000000
7,What is supervised learning?,0.0,0.0,0.0,0.000000
8,What is unsupervised learning?,0.0,0.0,0.0,0.000000
9,What is reinforcement learning?,0.0,0.0,0.0,0.000000
10,What is an LLM?,0.8,1.0,0.9,0.900000
11,What is Generative AI?,0.8,1.0,0.9,0.900000
12,What is a prompt?,0.8,0.8,0.9,0.833333
13,What is Prompt Engineering?,0.0,0.0,0.0,0.000000
14,What is RAG?,0.8,0.9,0.8,0.833333
15,Why is RAG useful?,0.8,0.9,0.9,0.866667
16,What is a vector database?,0.8,0.8,0.6,0.733333
17,What are embeddings?,0.6,0.8,0.4,0.600000
18,What is an AI Agent?,0.0,0.0,0.0,0.000000
19,How can AI be used in education?,0.8,0.9,0.8,0.833333

# STAGE 6 - EVALUATE SIMILARITY METRICS

In [10]:
similarity_scores = []

for _, row in tqdm(
    results_df.iterrows(),
    total=len(results_df),
    desc="Similarity metrics"
):
    reference = row["Teacher Response"]
    generated = row["GeneratedAnswer"]

    if not generated:
        similarity_scores.append([np.nan] * 5)
        continue

    try:
        _, _, f1 = bert_scorer.score(
            [generated],
            [reference]
        )
        bert = float(f1[0])
    except Exception:
        bert = np.nan

    try:
        rouge_scores = rouge.score(reference, generated)

        rouge1 = rouge_scores["rouge1"].fmeasure
        rouge2 = rouge_scores["rouge2"].fmeasure
        rougeL = rouge_scores["rougeL"].fmeasure
    except Exception:
        rouge1 = rouge2 = rougeL = np.nan

    try:
        meteor = meteor_score(
            [reference.split()],
            generated.split()
        )
    except Exception:
        meteor = np.nan

    similarity_scores.append([
        bert, rouge1, rouge2, rougeL, meteor
    ])


similarity_columns = [
    "BERT",
    "ROUGE-1",
    "ROUGE-2",
    "ROUGE-L",
    "METEOR"
]

results_df[similarity_columns] = pd.DataFrame(
    similarity_scores,
    index=results_df.index
)

display(results_df[["User Query"] + similarity_columns])

Similarity metrics:   0%|          | 0/20 [00:00<?, ?it/s]

,User Query,BERT,ROUGE-1,ROUGE-2,ROUGE-L,METEOR
0,What is AI?,0.913480,0.465116,0.190476,0.348837,0.446775
1,How does AI differ from traditional programming?,0.855624,0.185185,0.038462,0.074074,0.121951
2,What is Machine Learning?,0.833536,0.051282,0.000000,0.051282,0.018450
3,What is Deep Learning?,0.836621,0.000000,0.000000,0.000000,0.000000
4,"What is the difference between AI, ML, and Dee...",0.861886,0.232558,0.023810,0.162791,0.087977
5,What is training data?,0.842480,0.162162,0.000000,0.108108,0.059289
6,What is a Machine Learning model?,0.841404,0.000000,0.000000,0.000000,0.000000
7,What is supervised learning?,0.848262,0.176471,0.000000,0.117647,0.066372
8,What is unsupervised learning?,0.850146,0.242424,0.064516,0.181818,0.145449
9,What is reinforcement learning?,0.838834,0.068966,0.000000,0.068966,0.027624
10,What is an LLM?,0.907616,0.478873,0.260870,0.394366,0.546122
11,What is Generative AI?,0.928888,0.481481,0.269231,0.407407,0.421908
12,What is a prompt?,0.904031,0.363636,0.226415,0.327273,0.209736
13,What is Prompt Engineering?,0.841544,0.064516,0.000000,0.064516,0.025126
14,What is RAG?,0.935312,0.548387,0.400000,0.483871,0.535816
15,Why is RAG useful?,0.897450,0.357143,0.146341,0.285714,0.365143
16,What is a vector database?,0.915616,0.545455,0.129032,0.363636,0.243243
17,What are embeddings?,0.867012,0.290909,0.113208,0.254545,0.178405
18,What is an AI Agent?,0.835533,0.000000,0.000000,0.000000,0.000000
19,How can AI be used in education?,0.899348,0.358974,0.026316,0.205128,0.279701

# STAGE 7 - RAG EVALUATION METRICS

In [11]:
from bert_score import BERTScorer
from rouge_score import rouge_scorer
from nltk.translate.meteor_score import meteor_score
import nltk
import numpy as np
import pandas as pd

# Download once if needed
try:
    nltk.data.find("corpora/wordnet")
except LookupError:
    nltk.download("wordnet")


# ============================================================
# INITIALIZE METRICS
# ============================================================

bert_scorer = BERTScorer(
    lang="en",
    rescale_with_baseline=False
)

rouge = rouge_scorer.RougeScorer(
    ["rouge1", "rouge2", "rougeL"],
    use_stemmer=True
)


# ============================================================
# STORAGE
# ============================================================

similarity_results = []


# ============================================================
# EVALUATE
# ============================================================

for _, row in results_df.iterrows():

    reference = str(row["Teacher Response"])
    generated = str(row["GeneratedAnswer"])

    if not generated.strip():
        similarity_results.append({
            "BERTScore_P": np.nan,
            "BERTScore_R": np.nan,
            "BERTScore_F1": np.nan,
            "ROUGE1": np.nan,
            "ROUGE2": np.nan,
            "ROUGEL": np.nan,
            "METEOR": np.nan
        })
        continue


    # ========================================================
    # BERTSCORE
    # ========================================================

    P, R, F1 = bert_scorer.score(
        [generated],
        [reference]
    )

    bert_p = float(P[0])
    bert_r = float(R[0])
    bert_f1 = float(F1[0])


    # ========================================================
    # ROUGE
    # ========================================================

    rouge_scores = rouge.score(
        reference,
        generated
    )

    rouge1 = rouge_scores["rouge1"].fmeasure
    rouge2 = rouge_scores["rouge2"].fmeasure
    rougeL = rouge_scores["rougeL"].fmeasure


    # ========================================================
    # METEOR
    # ========================================================

    meteor = meteor_score(
        [reference.split()],
        generated.split()
    )


    similarity_results.append({
        "BERTScore_P": bert_p,
        "BERTScore_R": bert_r,
        "BERTScore_F1": bert_f1,

        "ROUGE1": rouge1,
        "ROUGE2": rouge2,
        "ROUGEL": rougeL,

        "METEOR": meteor
    })


# ============================================================
# ADD TO RESULTS
# ============================================================

similarity_df = pd.DataFrame(similarity_results)

results_df = pd.concat(
    [
        results_df.reset_index(drop=True),
        similarity_df.reset_index(drop=True)
    ],
    axis=1
)


display(
    results_df[
        [
            "User Query",
            "BERTScore_F1",
            "ROUGE1",
            "ROUGE2",
            "ROUGEL",
            "METEOR"
        ]
    ]
)

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\manju\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

,User Query,BERTScore_F1,ROUGE1,ROUGE2,ROUGEL,METEOR,METEOR
0,What is AI?,0.913480,0.465116,0.190476,0.348837,0.446775,0.446775
1,How does AI differ from traditional programming?,0.855624,0.185185,0.038462,0.074074,0.121951,0.121951
2,What is Machine Learning?,0.833536,0.051282,0.000000,0.051282,0.018450,0.018450
3,What is Deep Learning?,0.836621,0.000000,0.000000,0.000000,0.000000,0.000000
4,"What is the difference between AI, ML, and Dee...",0.861886,0.232558,0.023810,0.162791,0.087977,0.087977
5,What is training data?,0.842480,0.162162,0.000000,0.108108,0.059289,0.059289
6,What is a Machine Learning model?,0.841404,0.000000,0.000000,0.000000,0.000000,0.000000
7,What is supervised learning?,0.848262,0.176471,0.000000,0.117647,0.066372,0.066372
8,What is unsupervised learning?,0.850146,0.242424,0.064516,0.181818,0.145449,0.145449
9,What is reinforcement learning?,0.838834,0.068966,0.000000,0.068966,0.027624,0.027624
10,What is an LLM?,0.907616,0.478873,0.260870,0.394366,0.546122,0.546122
11,What is Generative AI?,0.928888,0.481481,0.269231,0.407407,0.421908,0.421908
12,What is a prompt?,0.904031,0.363636,0.226415,0.327273,0.209736,0.209736
13,What is Prompt Engineering?,0.841544,0.064516,0.000000,0.064516,0.025126,0.025126
14,What is RAG?,0.935312,0.548387,0.400000,0.483871,0.535816,0.535816
15,Why is RAG useful?,0.897450,0.357143,0.146341,0.285714,0.365143,0.365143
16,What is a vector database?,0.915616,0.545455,0.129032,0.363636,0.243243,0.243243
17,What are embeddings?,0.867012,0.290909,0.113208,0.254545,0.178405,0.178405
18,What is an AI Agent?,0.835533,0.000000,0.000000,0.000000,0.000000,0.000000
19,How can AI be used in education?,0.899348,0.358974,0.026316,0.205128,0.279701,0.279701

# STAGE 8 - OPERATIONAL METRICS SUMMARY

In [12]:
operational_columns = [
    "RetrievalLatency",
    "GenerationLatency",
    "Latency",
    "InputTokens",
    "OutputTokens",
    "TotalTokens",
    "InputCost",
    "OutputCost",
    "TotalCost"
]

operational_summary = pd.DataFrame({
    "Metric": operational_columns,
    "Average": [
        results_df[c].mean() for c in operational_columns
    ],
    "Total": [
        results_df[c].sum() for c in operational_columns
    ]
})

display(operational_summary.round(6))

              Metric     Average         Total
0   RetrievalLatency    1.905570     38.111395
1  GenerationLatency   16.095415    321.908291
2            Latency   18.001727    360.034537
3        InputTokens  600.000000  12000.000000
4       OutputTokens   32.550000    651.000000
5        TotalTokens  632.550000  12651.000000
6          InputCost    0.000000      0.000000
7         OutputCost    0.000000      0.000000
8          TotalCost    0.000000      0.000000